<?php

/**
 * DPRF.info
 * Arquivo responsável pelo carregamento das sugestões no campo de busca
 * 
 * @author Mário Pácio <mario.pacio@gmail.com>
 * @copyright 2013
 * @version 1.0
 * @package DPRF.info
 * @license AGPLv3 - http://www.gnu.org/licenses/agpl-3.0.html
 * 
 */
 

$infodprf_rodovias = array(
	array( // row #0
		'num_rodovia' => 10,
		'tipo_rodovia' => 0,
		'descricao' => 'A BR-010 ou Rodovia Bernardo Sayão, também conhecida populamente como Rodovia Belém-Brasília é uma rodovia federal radial do Brasil. \r\nSeu ponto inicial fica na cidade de Brasília (DF), e o final, em Belém (PA). Entre Brasília (DF) e Estreito (MA), \r\no percurso original da Rodovia Belém-Brasília segue pelas rodovias BR-060, BR-153 e BR-226, \r\nque são completamente asfaltadas neste trecho. A rodovia BR-010 passa pelo Distrito Federal, \r\nalém dos estados de Goiás, Tocantins, Maranhão e Pará. Em Goiás, a BR-010 é o principal acesso rodoviário à \r\nregião ecoturística da Chapada dos Veadeiros.',
	),
	array( // row #1
		'num_rodovia' => 20,
		'tipo_rodovia' => 0,
		'descricao' => 'A BR-020 é uma rodovia federal radial do Brasil. Seu ponto inicial fica na cidade de Brasília (Distrito Federal), e o final, \r\nem Fortaleza (Ceará). Passa pelo Distrito Federal e pelos estados de Goiás, Bahia, Piauí e Ceará. Nos estados da Bahia e do Piauí, \r\nhá longos trechos da rodovia que são de terra, e também trechos que não foram construídos até hoje, ainda estando na fase \r\nde planejamento, o que força os motoristas a utilizarem outras rodovias para chegarem ao seu destino.',
	),
	array( // row #2
		'num_rodovia' => 30,
		'tipo_rodovia' => 0,
		'descricao' => 'A BR-030 é uma Rodovia Federal radial do Brasil. Seu ponto inicial fica na cidade de Brasília (DF), e o final, em Maraú (BA). \r\nPassa pelo Distrito Federal e pelos Estados de Goiás, Minas Gerais e Bahia.\r\nA rodovia apresenta, ainda, vários trechos não construídos em Minas Gerais e na Bahia, onde o trecho compreendido entre Mirante (BA) \r\ne Boa Nova (BA), passando pela BR-116 é inexistente. Já o trecho final, entre Aurelino Leal e Barra Grande encontra-se em fase de implantação.\r\n<br />\r\nÀ altura de Caetité liga-se à BR-430, que vai até Barreiras e à BR-122.\r\n<br />\r\nA sua importância se deve ainda ao fato de passar pelo importante Vale do Iuiú, localizado na região da cidade de Iuiú, sudoeste baiano.',
	),
	array( // row #3
		'num_rodovia' => 40,
		'tipo_rodovia' => 0,
		'descricao' => 'A BR-040 é uma rodovia federal radial do Brasil. O ponto inicial da rodovia fica localizado em Brasília (DF), no entroncamento com a \r\nBR-450 (Via EPIA) e com a BR-251 (Via EPCT), enquanto que o ponto final fica localizado no Rio de Janeiro (RJ), \r\nmais especificamente na Praça Mauá. A BR-040 passa pelo Distrito Federal e pelos estados de Goiás, Minas Gerais e Rio de Janeiro, \r\nsendo a principal ligação rodoviária entre estas unidades federativas.',
	),
	array( // row #4
		'num_rodovia' => 50,
		'tipo_rodovia' => 0,
		'descricao' => 'A BR-050 é uma Rodovia Federal radial do Brasil. Seu ponto inicial fica na cidade de Brasília (DF), e o final, em Santos (SP). \r\nPassa pelo Distrito Federal e pelos Estados de Goiás, Minas Gerais e São Paulo. É considerada como uma das rodovias mais \r\nmovimentadas do país, pois liga a capital federal à maior metrópole brasileira, São Paulo.\r\n<br />\r\nO trecho paulista da rodovia encontra-se sob jurisdição do governo estadual, tendo a denominação SP-330 (Anhanguera) no \r\ntrecho que liga Igarapava a São Paulo e SP-150 (Anchieta) no trecho entre São Paulo e Santos.',
	),
	array( // row #5
		'num_rodovia' => 60,
		'tipo_rodovia' => 0,
		'descricao' => 'A BR-060 é uma rodovia federal radial brasileira. Seu ponto inicial fica na cidade de Brasília (DF), e o final, em Bela Vista (MS), \r\nna fronteira com o Paraguai. Passa pelo Distrito Federal e pelos Estados de Goiás e Mato Grosso do Sul.\r\n<br />\r\nA rodovia possui trechos não-asfaltados entre Jataí e Chapadão do Céu. É recomendável utilizar o caminho entre Rio Verde, \r\nItajá e Cassilândia, o único totalmente asfaltado.',
	),
	array( // row #6
		'num_rodovia' => 70,
		'tipo_rodovia' => 0,
		'descricao' => 'A BR-070 é uma rodovia federal radial brasileira. Seu ponto inicial fica na cidade de Brasília (DF), e o final, em Porto Corixó, \r\nno município de Cáceres (MT), na fronteira com a Bolívia. Passa pelo Distrito Federal e pelos Estados de Goiás e Mato Grosso.',
	),
	array( // row #7
		'num_rodovia' => 80,
		'tipo_rodovia' => 0,
		'descricao' => 'A BR-080 é uma rodovia radial brasileira que teoricamente ligaria a capital do país, Brasília, ao município de Ribeirão Cascalheira, \r\nno estado do Mato Grosso. No entanto, na prática, a rodovia se encontra construída atualmente apenas entre Brasília e o distrito \r\nde Luiz Alves, localizado em São Miguel do Araguaia (GO). Ao longo de seu percurso, a BR-080 passa pelo Distrito Federal e pelo \r\nestado de Goiás, podendo futuramente chegar até o Mato Grosso. O trecho da rodovia localizado entre Brasília (DF) e Uruaçu (GO) \r\né um dos principais trechos rodoviários da Região Centro-Oeste do Brasil, sendo responsável por ligar Brasília ao norte de Goiás, \r\nao Tocantins, ao Maranhão, ao Pará e ao Amapá, em conjunto com a BR-153. Em Goiás, há ainda um pequeno trecho localizado \r\nentre o povoado de São Cosme e Damião (em Bonópolis) e o distrito de Luiz Alves (em São Miguel do Araguaia). \r\n<br />\r\nO trechos localizados entre Uruaçu (GO) e o povoado de São Cosme e Damião (em Bonópolis, GO), assim como o trecho do estado \r\ndo Mato Grosso, ainda não chegaram a ser construídos.',
	),
	array( // row #8
		'num_rodovia' => 101,
		'tipo_rodovia' => 1,
		'descricao' => 'A BR-101, é uma rodovia federal longitudinal do Brasil. Seu ponto inicial está localizado na cidade de Touros (Rio Grande do Norte), \r\ne o final na cidade de São José do Norte (Rio Grande do Sul).\r\n<br />\r\nAtravessa doze estados brasileiros: Rio Grande do Norte, Paraíba, Pernambuco, Alagoas, Sergipe, Bahia, Espírito Santo, Rio de Janeiro, \r\nSão Paulo, Paraná, Santa Catarina e Rio Grande do Sul. Em toda sua extensão é denominada oficialmente Rodovia Governador \r\nMário Covas.\r\n<br />\r\nSegue no sentido norte-sul por praticamente todo o litoral leste brasileiro, do Rio Grande do Norte ao Rio Grande do Sul. \r\nTem dois trechos não construídos entre os municípios paulistas de Peruíbe e Iguape, e entre Cananeia (São Paulo) e Garuva \r\n(Santa Catarina).',
	),
	array( // row #9
		'num_rodovia' => 104,
		'tipo_rodovia' => 1,
		'descricao' => 'A BR-104 é uma rodovia federal longitudinal do Brasil. Seu ponto inicial fica na cidade de Macau (Rio Grande do Norte), e o fim, \r\nem Maceió (Alagoas). Passa pelos estados do Rio Grande do Norte, Paraíba, Pernambuco e Alagoas.\r\n<br />\r\nA rodovia apresenta, ainda, dois trechos não construídos no Estado do Rio Grande do Norte.',
	),
	array( // row #10
		'num_rodovia' => 110,
		'tipo_rodovia' => 1,
		'descricao' => 'A BR-110 é uma importante rodovia do nordeste do Brasil. \r\nComeça na cidade de Areia Branca no Rio Grande do Norte, passa por Mossoró e segue no sentido sul.\r\n<br />\r\nNa Paraíba, por sua vez, torna-se rodovia estadual (PB-110).',
	),
	array( // row #11
		'num_rodovia' => 116,
		'tipo_rodovia' => 1,
		'descricao' => 'A BR-116 é a principal rodovia brasileira, sendo também a maior rodovia totalmente pavimentada do país. \r\n<br />\r\nÉ uma rodovia longitudinal que tem início na cidade de Fortaleza, no estado do Ceará e término na cidade de Jaguarão, no estado \r\ndo Rio Grande do Sul, na fronteira com o Uruguai.\r\n<br />\r\nA extensão total da rodovia é de aproximadamente 4.385 quilômetros, passando por dez estados, ligando cidades importantes \r\ncomo Pelotas, Porto Alegre, Canoas, Caxias do Sul, Lages, Curitiba, São Paulo, Guarulhos, São José dos Campos, Volta Redonda, \r\nRio de Janeiro, Magé, Muriaé, Governador Valadares, Teófilo Otoni, Vitória da Conquista , Feira de Santana e Fortaleza.',
	),
	array( // row #12
		'num_rodovia' => 120,
		'tipo_rodovia' => 1,
		'descricao' => 'A BR-120 é uma rodovia federal longitudinal do Brasil que encontra-se com sua execução incompleta. \r\nSeu projeto original previa a ligação do município de Arraial do Cabo (RJ) à cidade de Araçuaí (MG). \r\nEla atravessaria os estados do Rio de Janeiro e de Minas Gerais. Em Minas Gerais, a BR-120 atravessa municípios importantes como \r\nViçosa e Itabira. Diversos trechos projetados ainda não estão implantados, principalmente seus pontos extremos. \r\n<br />\r\nRio de Janeiro, o único trecho existente da rodovia é o localizado entre Arraial do Cabo e São Pedro da Aldeia, \r\nque é administrado pelo governo do estado sob a denominação de RJ-140.',
	),
	array( // row #13
		'num_rodovia' => 122,
		'tipo_rodovia' => 1,
		'descricao' => 'A BR-122 é uma rodovia federal longitudinal do Brasil. Ela começa no estado do Ceará, em Fortaleza, e vai até o estado de Minas Gerais, \r\nno trevo da BR-251, que liga Montes Claros até a Rio-Bahia. Existem vários trechos sem pavimentação.',
	),
	array( // row #14
		'num_rodovia' => 135,
		'tipo_rodovia' => 1,
		'descricao' => 'A BR-135 é uma rodovia que liga o meio norte do Brasil (Maranhão) e termina em Belo Horizonte (Minas Gerais), \r\nsendo concorrente com a BR-040 entre o entroncamento das duas rodovias em Paraopeba e Belo Horizonte, em Minas Gerais.\r\n<br />\r\nEsta rodovia se encontra em péssimo estado de conservação no trecho norte mineiro, e não há asfaltamento por enquanto em \r\nvários trechos, principalmente na Bahia. Por ser uma rodovia que passa por regiões pobres e pouco desenvolvidas do Brasil \r\n(norte de Minas e todo o sertão nordestino), por muitas vezes foi esquecida pelo Governo Federal, estando em péssimo estado \r\nde conservação, ou sem projeto de pavimentação, em vários trechos.\r\n<br />\r\nEntre a cidade mineira de Montes Claros e o entroncamento com a BR 040, passando também por Curvelo, a rodovia recebeu nova pavimentação com a criação de terceira faixa em vários trechos, além da ampliação de pontes e de alças de acesso a municípios cortados pela estrada.',
	),
	array( // row #15
		'num_rodovia' => 146,
		'tipo_rodovia' => 1,
		'descricao' => 'A BR-146 é uma importante rodovia longitudinal que, quando concluída, ligará Patos de Minas a São Paulo (SP-8). \r\nO objetivo estratégico desta rodovia é ligar as regiões mineiras do Alto Paranaíba, Triângulo Mineiro e Sul de Minas com o Estado de \r\nSão Paulo, especialmente com porto de Santos e litoral paulista.\r\n<br />\r\nAlgus trechos desta rodovia, principalmente aqueles compreendidos entre Araxá e São João Batista do Glória, passarão ao norte e a \r\nleste do Parque Nacional da Serra da Canastra, impulsionando definitivamente o turismo nesta região, que vem se destacando no \r\nmercado brasileiro do eco-turismo.',
	),
	array( // row #16
		'num_rodovia' => 153,
		'tipo_rodovia' => 1,
		'descricao' => 'A BR-153, também conhecida pelos nomes de Rodovia Transbrasiliana, Rodovia Belém-Brasília e Rodovia Bernardo Sayão, \r\né a quarta maior rodovia do Brasil, ligando a cidade de Marabá (PA) ao município de Aceguá (RS), totalizando 4.355 quilômetros de \r\nextensão. Ao longo de todo o seu percurso, a BR-153 passa pelos estados do Pará, Tocantins, Goiás, Minas Gerais, São Paulo, \r\nParaná, Santa Catarina e Rio Grande do Sul. Os nomes de Rodovia Belém-Brasília e de Rodovia Bernardo Sayão, \r\nsão aplicados apenas no trecho localizado entre os entroncamentos com a BR-226 (em Wanderlândia, TO) e com a BR-060 \r\n(em Anápolis, GO). \r\n<br />\r\nA rodovia já foi chamada de BR-14 até o ano de 1964. Ao cruzar a fronteira com o Uruguai em Aceguá (RS), \r\na rodovia ainda segue por este país com a denominação de Rota 8, até chegar em Montevidéu. Entre Frutal (MG) e Wanderlândia (TO), \r\na BR-153 integra o tradicional trajeto rodoviário que liga São Paulo (SP) a Goiânia (GO) e a Belém (PA).',
	),
	array( // row #17
		'num_rodovia' => 154,
		'tipo_rodovia' => 1,
		'descricao' => 'A BR-154 é uma rodovia federal longitudinal brasileira. Ela começa no estado do Goiás e vai até o estado de São Paulo. \r\nDe Ituiutaba MG, até o encontro com a BR 364 em MG a estrada não está pavimentada.',
	),
	array( // row #18
		'num_rodovia' => 155,
		'tipo_rodovia' => 1,
		'descricao' => 'A BR-155 é uma rodovia federal que atualmente estende-se pela seção sudeste do estado do Pará, ligando as cidades entre Redenção \r\ne Marabá. Sua extensão atual é de aproximadamente 360 Km1 .\r\n<br />\r\nNo ano de 2010, a então parte sul da rodovia estadual Paulo Fontelles (PA-150), foi federalizada se tornando a BR-155. \r\nA PA-150 era considerada a estrada-tronco do Pará porque formava um importante eixo de integração com outras rodovias que \r\ninterligava o estado ao restante do território nacional.2',
	),
	array( // row #19
		'num_rodovia' => 156,
		'tipo_rodovia' => 1,
		'descricao' => 'A BR-156 é uma rodovia federal longitudinal brasileira, localizada no Amapá.\r\nTem início no município de Laranjal do Jari, vai até a capital do estado Macapá e termina em Oiapoque, à espera da conclusão da \r\nligação com a ponte sobre o Rio Oiapoque, já concluída em agosto de 2011, que ligará por via terrestre o Brasil e a Guiana Francesa.\r\n<br />\r\nSão 595 quilômetros entre o Oiapoque e Macapá, e 369 quilômetros entre Macapá e Laranjal do Jari (trecho via cidade de Santana), \r\ntotalizando 964 quilômetros de estrada, que cortam o cerrado e a floresta. Destes, apenas 347 quilômetros, entre Macapá e Calçoene, \r\npossem asfalto. O resto da estrada ainda possui pavimentação de terra.\r\n<br />\r\nEsta rodovia está sendo construída desde os anos 1940 e não há previsão de quando será terminada.',
	),
	array( // row #20
		'num_rodovia' => 158,
		'tipo_rodovia' => 1,
		'descricao' => 'A BR-158 é uma rodovia longitudinal federal brasileira que atravessa o país de norte a sul.\r\n<br />\r\nSeu ponto inicial localiza-se entre as rodovias BR-230 e PA-415 no município de Altamira no estado do Pará. Passa depois pelos estados \r\ndo Mato Grosso, Goiás, Mato Grosso do Sul, São Paulo, Paraná, Santa Catarina e Rio Grande do Sul, onde encontra seu término na \r\nfronteira com o Uruguai, no município de Santana do Livramento.\r\n<br />\r\nNo trecho em que a rodovia liga os estados de São Paulo e Mato Grosso do Sul, utiliza-se da Ponte Rodoferroviária sobre o Rio Paraná, \r\ncom 2.600 metros de extensão.\r\n<br />\r\nCuriosamente, ao contrário da maioria das rodovias longitudionais, ela não atravessa nenhuma capital brasileira.',
	),
	array( // row #21
		'num_rodovia' => 163,
		'tipo_rodovia' => 1,
		'descricao' => 'A BR-163 é uma rodovia longitudinal do Brasil. Tem 3467 km de extensão, sendo quase 1000 km não asfaltados. Liga Tenente Portela, \r\nno Rio Grande do Sul, a Santarém, no Pará.\r\n<br />\r\nÉ uma rodovia que integra o Sul ao Centro Oeste e Norte do Brasil. É asfaltada até Mato Grosso, na cidade de Guarantã do Norte, \r\na 728 km da capital Cuiabá, no extremo norte do estado. Daí, sentido Santarém, PA, são 1010 km de estradas de chão. Possui \r\nfundamental importância para o escoamento da produção da parte paraense da Região Norte e norte da Região Centro-Oeste do Brasil.\r\n<br />\r\nDesde 2009 a BR-163 conta com o policiamento de mais 340 agentes da Polícia Rodoviária Federal (PRF), a qual já conta com bases \r\nespalhadas pela rodovia, além das que estão em fase de construção para receber os novos policiais.\r\n<br />\r\nEstima-se que até 80% da estrada está re-pavimentada.',
	),
	array( // row #22
		'num_rodovia' => 174,
		'tipo_rodovia' => 1,
		'descricao' => 'A BR-174, também conhecida por Manaus–Boa Vista, é uma rodovia longitudinal que interliga os estados brasileiros de Roraima e \r\nAmazonas à Venezuela, num total de 974 quilômetros. \r\n<br />\r\nTem como extremos as cidades de Manaus e Pacaraima. É a única ligação de Roraima com o resto do país, sendo sua maior e principal \r\nrodovia. Embora iniciada na ditadura militar, a conclusão de seu asfaltamento e sinalização deu-se somente em 1998.',
	),
	array( // row #23
		'num_rodovia' => 210,
		'tipo_rodovia' => 2,
		'descricao' => 'A BR-210, também conhecida como Perimetral Norte, é uma rodovia federal brasileira projetada para atender aos estados de Amazonas, \r\nPará, Amapá e Roraima. Até hoje somente foram implantados trechos nos dois últimos estados citados.\r\n<br />\r\nEm Roraima, a BR-210 possui hoje 411,7 quilômetros abertos, saindo do rio Jatapu à Missão Catrimani. \r\nTodo este trecho encontra-se asfaltado, embora muitos segmentos em estado crítico de conservação. \r\nConecta as cidades de Caroebe, São João da Baliza, São Luiz e Caracaraí, além de diversas vilas.\r\n<br />\r\nNo seu trajeto roraimense intercepta as federais BR-174 e BR-432, as estaduais RR-460 e RR-344, além de diversas estradas vicinais \r\nde administração municipal.',
	),
	array( // row #24
		'num_rodovia' => 222,
		'tipo_rodovia' => 2,
		'descricao' => 'A BR-222 é uma rodovia federal que estende-se atualmente de Fortaleza, capital do Ceará à cidade de Marabá, no Pará, interligando, \r\nalém de Ceará e Pará, os estados de Piauí e Maranhão. Apresenta trechos em péssimo estado de conservação. \r\nSua extensão atual é de 1811,6 Km.\r\n<br />\r\nPassa por grandes centros urbanos, como Fortaleza e Teresina, ligando regiões ricas economicamente, como sudeste do estado \r\ndo Pará ao restante do Brasil.',
	),
	array( // row #25
		'num_rodovia' => 226,
		'tipo_rodovia' => 2,
		'descricao' => 'A BR-226 é uma rodovia transversal brasileira que liga a cidade de Natal (RN), ao município de Wanderlândia (TO). Ao longo de todo o \r\nseu percurso, a BR-226 passa pelos estados do Rio Grande do Norte, Ceará, Piauí, Maranhão e Tocantins. \r\nA extensão total da rodovia é de 1674,6 km.\r\n<br />\r\nA BR-226 passa dentre outras, pelas cidades de Natal, Currais Novos, Florânia, Pau dos Ferros, Pedra Branca, Crateús, Teresina, \r\nTimon, Grajaú, Porto Franco, Estreito, Aguiarnópolis e Wanderlândia.\r\n<br />\r\nA rodovia possui diversos trechos ainda não asfaltados ou não implantados.',
	),
	array( // row #26
		'num_rodovia' => 230,
		'tipo_rodovia' => 2,
		'descricao' => 'A Rodovia Transamazônica (BR-230) é uma rodovia brasileira, projetada durante o governo do presidente Emílio Garrastazu Médici \r\n(1969 a 1974), sendo uma das chamadas "obras faraônicas" devido às suas proporções gigantescas, realizadas pelo regime militar.\r\n<br />\r\nÉ a terceira maior rodovia do Brasil, com 4 223 km de comprimento, ligando Cabedelo, na Paraíba à Lábrea, no Amazonas, cortando \r\nsete estados brasileiros; Paraíba, Ceará, Piauí, Maranhão, Tocantins, Pará e Amazonas. Nasce na cidade de Cabedelo, na Paraíba, \r\ne segue até Lábrea, no Amazonas.\r\n<br />\r\nÉ classificada como rodovia transversal. Em grande parte, principalmente no Pará e no Amazonas, a rodovia não é pavimentada.',
	),
	array( // row #27
		'num_rodovia' => 232,
		'tipo_rodovia' => 2,
		'descricao' => 'A BR-232 é uma rodovia brasileira que se inicia em Recife, Pernambuco e parte rumo ao interior de Pernambuco, terminando em \r\nParnamirim. Tem uma extensão de aproximadamente 552 km, desde o fim do viaduto de contorno sobre a BR 101 (Recife), \r\naté a bifurcação entre a BR 316 e a Rua Dirceu Possídio, em Parnamirim. Parte da antiga BR-25, teve sua denominação alterada em \r\n1964 para a nomenclatura atual.\r\n<br />\r\nFoi duplicada no governo de Jarbas Vasconcelos no trecho mais movimentado, entre Recife, Caruaru e São Caetano.\r\n<br />\r\nMuito usada no transporte de carga entre Recife e os estados do Piaui, Maranhão, Tocantins e oeste da Bahia.',
	),
	array( // row #28
		'num_rodovia' => 235,
		'tipo_rodovia' => 2,
		'descricao' => 'A BR-235 é uma rodovia transversal brasileira que liga Aracaju, em Sergipe, ao Campo de Provas Brigadeiro Velloso em Novo Progresso, \r\nno Pará. Ao longo do seu percurso, atravessa os estados de Sergipe, Bahia, Pernambuco, Piauí, Maranhão, Tocantins, além do Pará.\r\n<br />\r\nÉ uma das rodovias mais complicadas do Brasil, pois não há asfalto na maior parte da rodovia, e ainda há muitos trechos inexistentes. \r\nBasicamente só há asfalto no Estado do Sergipe, entre as cidades de Petrolina(PE) e Remanso(BA), e no trecho entre Guaraí(TO) \r\ne Santa Maria do Tocantins(TO). No Maranhão ainda não há nenhum trecho construído da rodovia, enquanto que no Pará o único \r\ntrecho existente é o pequeno trecho de 21 km entre a travessia do rio Araguaia (via balsa) e a cidade de Santa Maria das Barreiras.',
	),
	array( // row #29
		'num_rodovia' => 242,
		'tipo_rodovia' => 2,
		'descricao' => 'A BR-242 é uma rodovia transversal brasileira. Ela se estende do estado da Bahia (mais precisamente da localidade de São Roque do \r\nParaguaçu, no município de Maragogipe), passando pela BR-101 entre os municípios de Conceição do Almeida, Sapeaçu e Castro Alves, \r\ncruzando com a BR-116 na localidade de Paraguaçu (no município de Rafael Jambeiro) e com a BR-153 no trecho entre os municípios de \r\nGurupi - TO e Cariri do Tocantins - TO, seguindo até o estado do Mato Grosso (no município de Sorriso). A rodovia ainda possui muitos \r\ntrechos sem pavimentação ou ainda por construir, principalmente nos estados do Mato Grosso e do Tocantins. No estado da Bahia, \r\na BR-242 é a principal via de acesso à região ecoturística da Chapada Diamantina. A rodovia passa logo ao lado de um dos principais \r\ncartões-postais da Chapada Diamantina, que é o Morro do Pai Inácio. O total de sua extensão é de 2311,7 km e liga cidades \r\nrelativamente importantes, tais como: Itaberaba - BA, Lençóis - BA (a apenas 11 km da rodovia), Seabra - BA, Barreiras - BA, \r\nLuís Eduardo Magalhães - BA, Gurupi - TO e a própria cidade de Sorriso - MT. As principais travessias fluviais da rodovia são: \r\na travessia sobre o Rio São Francisco, em Ibotirama (BA); a travessia sobre o Rio Tocantins, em Peixe (TO); a travessia sobre o \r\nRio Javaés, em Formoso do Araguaia (TO); e a travessia de balsa sobre o Rio Araguaia, em São Félix do Araguaia (MT).',
	),
	array( // row #30
		'num_rodovia' => 251,
		'tipo_rodovia' => 2,
		'descricao' => 'A BR-251, ou oficialmente Rodovia Júlio Garcia, é uma rodovia transversal brasileira.\r\n<br />\r\nEla estende-se do estado da Bahia até o estado de Mato Grosso. O total de sua extensão é de aproximadamente 1515,2 Km. \r\nEm geral, apresenta problemas de conservação em vários trechos. É a unica rodovia transversal que corta o Distrito Federal.\r\n<br />\r\nA BR 251 ainda possui muitos trechos não asfaltados ou não implantados, principalmente no estado do Mato Grosso.\r\n<br />\r\nOs trechos já implantados, e mais utilizados, da BR 251 são os que ligam Montes Claros à BR 116 (Rio-Bahia), e o que liga Unaí ao \r\nDistrito Federal.',
	),
	array( // row #31
		'num_rodovia' => 259,
		'tipo_rodovia' => 2,
		'descricao' => 'A BR-259 é uma rodovia federal transversal do Brasil que interliga o estado do Espírito Santo a Minas Gerais.\r\n<br />\r\nPercorre 106,3 km no estado do Espírito Santo (começando na BR-101, na altura do município de João Neiva) e 605,4 km no estado de \r\nMinas Gerais, onde passa por cidades como Governador Valadares, importante centro regional. Termina na BR-040, no município de \r\nFelixlândia), totalizando 711,7 km.',
	),
	array( // row #32
		'num_rodovia' => 262,
		'tipo_rodovia' => 2,
		'descricao' => 'A BR-262 é um rodovia transversal brasileira que interliga os estados do Espírito Santo, Minas Gerais, São Paulo e Mato Grosso do Sul.\r\n<br />\r\nComeça em Vitória no estado do Espírito Santo, passa por cidades importantes como Belo Horizonte, Araxá, Uberaba, Três Lagoas e \r\nCampo Grande e termina junto à fronteira com a Bolívia, em Corumbá no estado de Mato Grosso do Sul.\r\n<br />\r\nPercorre 195,5 km no estado do Espírito Santo, 999,8 km no estado de Minas Gerais, 316,7 km no estado de São Paulo e 783 km no \r\nestado de Mato Grosso do Sul. O trecho paulista ainda não é reconhecido, apesar de aparentemente o traçado ser coincidente com o \r\nda SP-300 no trecho entre Nhandeara e Ilha Solteira.\r\n<br />\r\nEntre Betim, na região metropolitana de Belo Horizonte, e João Monlevade, a BR-262 e a BR-381 se unem, formando uma única rodovia.\r\n<br />\r\nO trecho de Betim a Nova Serrana já está no término da duplicação. São 84 km de rodovia duplicada.',
	),
	array( // row #33
		'num_rodovia' => 265,
		'tipo_rodovia' => 2,
		'descricao' => 'A BR-265 é uma rodovia federal do Brasil. Seu ponto inicial efetivo fica na cidade de Rio Pomba (MG) e o planejado na cidade de Muriaé. \r\nO ponto final pavimentado da rodovia é a cidade de Ilicínea. Entretanto, tem-se planejado o restante do trecho (Ilicínea-MG até \r\nSão José do Rio Preto-SP). Com o futuro ligamento até Muriaé, servirá de rota entre São Paulo e o Nordeste, uma vez que se \r\nentroncará com a BR-116 em Muriaé, em Lavras a BR-381 (Fernão Dias) e em Barbacena com a BR-040.',
	),
	array( // row #34
		'num_rodovia' => 267,
		'tipo_rodovia' => 2,
		'descricao' => 'A BR-267, oficialmente Rodovia Presidente Itamar Franco, é uma rodovia transversal que corta os estados brasileiros de Minas Gerais, \r\nSão Paulo e Mato Grosso do Sul.\r\n<br />\r\nInicia-se no município de Leopoldina, Minas Gerais, no entroncamento com a Rodovia BR-116 e prossegue até a fronteira do Brasil com o \r\nParaguai em Porto Murtinho, Mato Grosso do Sul.\r\n<br />\r\nA BR-267 possui extensão total de 1922 quilômetros, sendo 533 em Minas Gerais, 706 em São Paulo e 683 no Mato Grosso do Sul. Em \r\nMinas Gerais, no trecho entre Juiz de Fora e Campanha, é denominada Rodovia Vital Brazil.',
	),
	array( // row #35
		'num_rodovia' => 272,
		'tipo_rodovia' => 2,
		'descricao' => 'A BR-272 é uma rodovia transversal brasileira que liga São Paulo até a divisa do Estado do Paraná (Guaíra), fronteira com a República \r\ndo Paraguai.\r\n<br />\r\nExistem muitos trechos que estão apenas planejados, isto é, ainda não foram efetivamente construídos, no estado do Paraná.\r\n<br />\r\nEm 2006, passou por um processo de recapeamento entre os municípios de Campo Mourão e Goioerê, no Estado do Paraná, \r\no seu primeiro desde a inauguração deste trecho.',
	),
	array( // row #36
		'num_rodovia' => 277,
		'tipo_rodovia' => 2,
		'descricao' => 'A BR-277, também denominada como Grande Estrada, é uma rodovia federal transversal do Brasil. Foi inaugurada em março de 1969, \r\ne tem 730 km de extensão, com início no Porto de Paranaguá e término na Ponte da Amizade, em Foz do Iguaçu. Saindo de Curitiba, \r\na rodovia se sobrepõe a Rodovia do Café, até sua interação com seu trajeto original no km 140. Administrada por três concessionárias \r\ndiferentes, ao longo de distintos trechos da mesma, está duplicada de Paranaguá a sua interseção com a BR-376 no km 140, e de \r\nMedianeira à Foz do Iguaçu.',
	),
	array( // row #37
		'num_rodovia' => 280,
		'tipo_rodovia' => 2,
		'descricao' => 'A BR-280 é uma rodovia transversal brasileira. Tem início na cidade catarinense de São Francisco do Sul e término na cidade catarinense \r\nde Dionísio Cerqueira, na fronteira com a Argentina. O total de sua extensão é de aproximadamente 634,1 Km.\r\n<br />\r\nPartindo de São Francisco do Sul, atravessa cidades importantes do extremo norte de Santa Catarina, como Joinville, Jaraguá do Sul, \r\nSão Bento do Sul, Rio Negrinho, Mafra, Canoinhas e Porto União até o estado de Paraná, na qual pecorre-se o extremo sul desse \r\nestado, atravessando outros importantes municípios como Pato Branco, Palmas, Francisco Beltrão e Clevelândia.\r\n<br />\r\nAtravessa a BR-163 a poucos quilômetros da divisa da Argentina, próximos aos municípios de Dionísio Cerqueira (SC) e Barracão (PR), \r\na BR-153, na altura de União da Vitória (PR), a BR-116 em Mafra (SC) e a BR-101 em Joinville (SC). No trecho leste cruza com algumas \r\nrodovias estaduais catarinenses, como a SC-301 em Araquari e São Bento do Sul, a SC-416 em Jaraguá do Sul, a SC-413 em Guaramirim, \r\ne a SC-422 em Rio Negrinho, dentre outras.\r\n<br />\r\nHá projeto de duplicação da rodovia no trecho entre Jaraguá do Sul e São Francisco do Sul, em Santa Catarina, que também prevê \r\nmudança no seu traçado, que deixará de passar pelo perímetro urbano central de Jaraguá do Sul, voltando a ser pista única próximo \r\nda divisa deste município com Corupá.\r\n<br />\r\nA rodovia é muito importante na região para o escoamento das safras agrícolas e produtos industrializados, sobretudo, para o Porto de \r\nSão Francisco do Sul (SC).\r\n<br />\r\nUm de seus trechos mais críticos é a Serra do Mar, em Corupá, com constantes deslizamentos de terra nas épocas de chuvas.',
	),
	array( // row #38
		'num_rodovia' => 282,
		'tipo_rodovia' => 2,
		'descricao' => 'A BR-282 é uma rodovia transversal no Sul do Brasil. Seu projeto oficial contempla a ligação entre Florianópolis (SC) e Paraíso (SC) \r\n(divisa com Argentina). É uma rodovia de pista simples, sendo duplicada nos seus primeiros 6,5;km iniciais,e os 14 Km no trecho urbano \r\nde Xanxerê e o acesso a Chapecó estão em obras de duplicação. Também no perímetro urbano de Lages, estão sendo construídas \r\nvias marginais e viadutos, além disso um trecho está sendo duplicado, num total de 6 kms de obras. Entre Florianópolis e São José, \r\na BR recebe o nome de "Via Expressa". Sobrepõe-se à BR-101 no trecho entre São José e Palhoça onde torna a separar-se seguindo \r\nem sentido oeste inicialmente pelo Vale do Rio Cubatão, atravessa a região da Grande Florianópolis vencendo a Serra Geral, \r\nprossegue passando pelo planalto sul, meio-oeste, oeste, extremo-oeste atingindo a fronteira com a República argentina. \r\nMuitas vezes chamada de "corredor do Mercosul" faz a ligação leste-oeste cruzando todo o estado de Santa Catarina. \r\n<br />\r\nA BR conta com apenas uma balança que fica na cidade de Maravilha e vários postos da Policia Rodoviaria Federal, também conta com \r\nvários hotéis e restaurantes ao longo da rodovia.\r\n<br />\r\nCidades importantes próximas à rodovia: Florianópolis, São José, Palhoça, Santo Amaro da Imperatriz, Alfredo Wagner, Lages, \r\nCampos Novos, Joaçaba, Xanxerê, Xaxim, Chapecó, Pinhalzinho, Maravilha, São Miguel do Oeste e Paraíso.\r\n<br />\r\nAlgumas rodovias tem seu traçado sob a rodovia como a BR-480 a BR-101 e a BR-163 entre outras.',
	),
	array( // row #39
		'num_rodovia' => 283,
		'tipo_rodovia' => 2,
		'descricao' => 'A SC-283 ou BR-283 (comumente chamada de SC-283) é uma rodovia transversal brasileira. Ela fica no estado de Santa Catarina \r\ne atravessa a cidade de Chapecó. O total de sua extensão é de 362,7 Km.',
	),
	array( // row #40
		'num_rodovia' => 285,
		'tipo_rodovia' => 2,
		'descricao' => 'A BR-285 é uma rodovia transversal brasileira que inicia em Araranguá, Santa Catarina, atravessa a serra e o planalto gaúchos, \r\ntem uma extensão de aproximadamente 674,5 km, passando por cidades como Vacaria, Lagoa Vermelha, Passo Fundo, Carazinho, \r\nIjuí e São Luiz Gonzaga e termina em São Borja, Rio Grande do Sul, na fronteira com a Argentina.\r\n<br />\r\nDurante o veraneio, a BR-285 recebe grande fluxo de veículos de passeio provindos da Argentina, em direção ao Litoral Gaúcho e \r\nCatarinense. O trajeto é feito entre São Borja (divisa com a Argentina) até Vacaria. De lá, o motorista pode seguir para as praias \r\ngaúchas, descendo para Caxias do Sul e tomando a Rota do Sol até Terra de Areia. Outro caminho é subir até Lages, já no estado \r\nde Santa Catarina, e dali seguir direto para Florianópolis. O trajeto entre Vacaria e Araranguá, além de ser realizado em trecho de \r\nserra e com baixa infra-estrutura viária, ainda tem um trecho não-asfaltado entre as cidades de São José dos Ausentes e Timbé do Sul, \r\no que torna este trecho de muito baixo movimento.\r\n<br />\r\nFoi construída pelo 3º Batalhão Rodoviário e funcionários públicos federais contratados na época, com início no município de Vacaria-RS, \r\ncujo marco do quilometro "zero" foi implantado naquele município, sendo posteriormente alterado, quando a mesma foi ampliada até o \r\nmunicípio de Araranguá-SC.',
	),
	array( // row #41
		'num_rodovia' => 287,
		'tipo_rodovia' => 2,
		'descricao' => 'A BR 287 é uma rodovia federal que corta transversalmente o estado brasileiro do Rio Grande do Sul. A rodovia também é conhecida \r\ncomo Rodovia da Integração.\r\n<br />\r\nInicia na Região de Porto Alegre, na cidade de Canoas. Passan pelo Centro Oriental,Centro Ocidental e terminando na região Sudoeste, \r\nna cidade de São Borja. Sua extensão é de 536,9 km.\r\n<br />\r\nQuase toda a rodovia BR-287, cruza o Geoparque Paleorrota, sendo o principal eixo de ligação das dezenas de municípios da região \r\nque contem fosseis. Nas regiões Centro Oriental e Centro Ocidental estão os principiais municípios com fosseis. \r\n<br />\r\nO desenvolvimento do turismo na região beneficiaria 8% da população do Rio Grande do Sul.',
	),
	array( // row #42
		'num_rodovia' => 290,
		'tipo_rodovia' => 2,
		'descricao' => 'A BR-290 - Rodovia Osvaldo Aranha, é uma das mais importantes rodovias do Brasil, com 726km de extensão, situada no estado do \r\nRio Grande do Sul que atravessa o litoral norte do estado em sentido oeste, até o município de Uruguaiana, na divisa com a Argentina.\r\n<br />\r\nO trecho entre o inicio da rodovia, junto à BR-101 no município de Osório até a capital do estado, Porto Alegre, é conhecida \r\ncomo Free-way. Este trecho possui dois pedágios, um em Gravataí e outro em Santo Antônio da Patrulha (este sendo cobrado \r\napenas no sentido Litoral); e apresenta tráfego intenso, com três faixas de rodagem em cada sentido.\r\n<br />\r\nEntre a zona norte de Porto Alegre e o município de Guaíba ocorre a sobreposição com a BR-116.',
	),
	array( // row #43
		'num_rodovia' => 293,
		'tipo_rodovia' => 2,
		'descricao' => 'A BR-293 é uma rodovia transversal brasileira. Ela se localiza no estado do Rio Grande do Sul e interliga Pelotas a Quaraí, atravessando \r\nimportantes municípios do extremo sul brasileiro como Bagé e Santana do Livramento. O total de sua extensão é de aproximadamente \r\n535,7 km.',
	),
	array( // row #44
		'num_rodovia' => 304,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-304 é uma rodovia federal brasileira diagonal que liga Natal, capital do Rio Grande do Norte, até Russas1 , no estado do Ceará. \r\nDe lá, é possível pegar a BR-116 e ir até Fortaleza, capital do Ceará.\r\n<br />\r\nA rodovia passa por Mossoró, a segunda cidade mais populosa do Rio Grande do Norte.',
	),
	array( // row #45
		'num_rodovia' => 307,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-307 é uma rodovia federal diagonal brasileira. Teoricamente, ela se inicia no município de Marechal Thaumaturgo, no Acre, \r\ne segue até o distrito de Cucuí, em São Gabriel da Cachoeira, no Amazonas. Foi projetada durante a ditadura militar e estima-se \r\nque jamais será concluída, já que o governo brasileiro passou a adotar políticas de conservação ambiental nos últimos anos. \r\n<br />\r\nAlém disso, o traçado da BR-307 atravessa regiões habitadas por índios isolados, notadamente na região do Vale do Javari \r\n(trecho Cruzeiro do Sul - Atalaia do Norte).',
	),
	array( // row #46
		'num_rodovia' => 308,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-308 ou rodovia Transoceânica é uma rodovia federal diagonal brasileira. Liga o município de Capanema no estado do Pará, \r\nao município de Alcântara no estado do Maranhão. Somente alguns trechos isolados no Maranhão foram realmente concluídos, \r\nao contrário dos trechos no Pará (Capanema - Viseu), que estão todos concluídos, embora ainda não asfaltados em sua totalidade.',
	),
	array( // row #47
		'num_rodovia' => 316,
		'tipo_rodovia' => 3,
		'descricao' => 'A rodovia BR-316, é uma rodovia federal diagonal do Brasil. Seu ponto inicial está localizado na cidade de Belém (Pará), e o final \r\nna cidade de Maceió (Alagoas).',
	),
	array( // row #48
		'num_rodovia' => 317,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-317 é uma rodovia federal diagonal brasileira. Liga o município de Boca do Acre, localizado no Estado do Amazonas, à Rio Branco, \r\ncapital do Acre, e segue até Assis Brasil, município acreano localizado na tripla fronteira Brasil-Peru-Bolívia.\r\n<br />\r\nToda a pavimentação da BR-317 era de terra, mas o trecho entre Rio Branco e Assis Brasil, de 331 km, foi completamente asfaltado \r\nno Governo FHC.',
	),
	array( // row #49
		'num_rodovia' => 319,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-319 é uma rodovia federal diagonal brasileira, que liga as cidades de Manaus (AM) e Porto Velho (RO), na Região Norte do Brasil. \r\n<br />\r\nAo longo do seu percurso, a rodovia passa pelos estados brasileiros do Amazonas e de Rondônia. A BR-319 é a única ligação rodoviária \r\ndisponível entre Manaus e o estado de Rondônia, com todo o restante do Brasil. O trecho entre Manaus e a localidade de Havelândia \r\n(no limite de município entre Manicoré e Beruri) é concomitante com a BR-174.',
	),
	array( // row #50
		'num_rodovia' => 324,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-324 é uma rodovia federal brasileira que parte de Balsas, Maranhão e termina em Salvador - Bahia.\r\n<br />\r\nEla desempenha uma importante função que é interligar o entroncamento rodoviário em Feira de Santana à Salvador, tornando-a \r\numa das principais rodovias no estado da Bahia.',
	),
	array( // row #51
		'num_rodovia' => 330,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-330 é uma rodovia federal diagonal brasileira. Liga BR-101 no município de Ubaitaba (BA), passando pelos municípios de Ubatã, \r\nBarra do Rocha, Ipiaú, Jitaúna até Jequié na BR-116.',
	),
	array( // row #52
		'num_rodovia' => 342,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-342 é uma rodovia federal diagonal brasileira.\r\n<br />\r\nA rodovia liga Carinhanha, no sudoeste da Bahia, à Sooretama, no Espírito Santo, passando pelo nordeste de Minas Gerais. \r\nEsta rodovia ainda possui vários trechos ainda não pavimentados ou não implantados, possuindo poucos trechos asfaltados.',
	),
	array( // row #53
		'num_rodovia' => 343,
		'tipo_rodovia' => 3,
		'descricao' => 'BR 343 é uma rodovia diagonal do estado do Piauí, no Brasil, que liga a cidade de Luís Correia à Bertolínia.\r\n<br />\r\nÉ muito importante para o desenvolvimento do estado, pois liga a capital do estado (Teresina) ao litoral, além de interligar o \r\nPiauí ao Ceará, no entroncamento com a BR-404.',
	),
	array( // row #54
		'num_rodovia' => 349,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-349 é uma rodovia federal diagonal brasileira, que interliga a BR-020, na altura da divisa entre os estados de Goiás e Bahia, \r\nindo até a cidade de Aracaju, capital de Sergipe.\r\n<br />\r\nPossui asfalto da divisa até Bom Jesus da Lapa, quando se une à BR-430, através da Ponte Gercino Coelho. Novo trecho asfaltado está \r\nna cidade baiana de Seabra e depois somente nas proximidades de Aracaju, quando encontra a BR-235, sendo que, portanto, \r\na grande maioria de seu trajeto é planejado.',
	),
	array( // row #55
		'num_rodovia' => 352,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-352 é uma rodovia federal diagonal brasileira. Possui aproximadamente 800 km de extensão e liga Goiânia \r\n(capital do Estado de Goiás) à BR-262 próximo ao município de Pará de Minas (Estado de Minas Gerais), já quase em Belo Horizonte.\r\n<br />\r\n O seu traçado, no entanto não está completo, sendo que existem trechos sem pavimentação e outros ainda a serem implantados, \r\nmas já planejados. Os trechos ainda não implantados totalmente ficam entre Abaeté(MG) e Arapuá(MG), e entre Patos de Minas(MG) \r\ne a divisa MG/GO.',
	),
	array( // row #56
		'num_rodovia' => 354,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-354 é uma rodovia federal diagonal brasileira. Esta rodovia tem início em Resende-RJ em um viaduto sobre o km 330 da Rodovia \r\nPresidente Dutra e termina seu primeiro trecho em Caxambu-MG, onde encontra-se com a BR-267, porém a rodovia prossegue até \r\nCristalina-GO.\r\n<br />\r\nA BR-354 é a estrada federal (asfaltada) mais alta do Brasil. Sinuosa e bela, chega a uma altitude de 1670m na divisa entre os Estados \r\ndo Rio de Janeiro e de Minas Gerais (Resende-RJ/Itamonte-MG), num ponto denominado Garganta do Registro. Neste local também \r\nse encontra a entrada da BR-485, que segue até a parte alta do Parque Nacional de Itatiaia. \r\n<br />\r\nA BR-354 atravessa as cidades mineiras de Itamonte e Pouso Alto, é ainda a principal rota de ligação entre o estado do Rio de Janeiro \r\ne a região do Sul de Minas, onde encontram-se importantes cidades como Pouso Alegre, São Lourenço e Guaxupé.',
	),
	array( // row #57
		'num_rodovia' => 356,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-356 é uma rodovia federal diagonal, com o seu sentido crescente de noroeste a sudeste.\r\n<br />\r\nSeu ponto inicial está em Belo Horizonte (MG); o ponto final está em São João da Barra (RJ).\r\n<br />\r\nAssim, tendo um total de 472,9 km de extensão, passa em Minas Gerais, com 288,3 km, cortando treze municípios, e no Rio de Janeiro, \r\ncom 187,7 km, em outros cinco municípios.',
	),
	array( // row #58
		'num_rodovia' => 359,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-359 é uma rodovia federal diagonal brasileira.',
	),
	array( // row #59
		'num_rodovia' => 361,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-361 é uma rodovia federal diagonal brasileira, localizado no Sertão Nordestino.',
	),
	array( // row #60
		'num_rodovia' => 363,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-363 é uma rodovia federal diagonal brasileira. Liga o Porto de Santo Antônio à Praia do Sueste, em Vila dos Remédios, \r\nFernando de Noronha, com seus 7 km, sendo assim a segunda menor rodovia federal do Brasil, atrás apenas da BR-488. \r\nÉ a única rodovia existente em toda a ilha.',
	),
	array( // row #61
		'num_rodovia' => 364,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-364 é uma importante rodovia diagonal do Brasil que se inicia em Limeira-SP, no km 153 da SP-330 adentrando pela SP-310 até o \r\nkm 292, onde entra na SP-326 indo até a divisa com Minas Gerais, depois passa por Goiás, Mato Grosso, Rondônia e Acre acabando \r\nem Rodrigues Alves, no extremo-oeste deste estado sendo assim uma rodovia de fundamental importância para o escoamento da \r\nprodução de toda a região Norte e Centro Oeste do País.',
	),
	array( // row #62
		'num_rodovia' => 365,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-365 é uma importante rodovia diagonal federal brasileira que liga as regiões Nordeste - Centro Oeste. A BR-365 liga duas \r\ncidades importantes de Minas Gerais: Montes Claros - Uberlândia, além de ligar Uberlândia a BR-364 (divisa de Minas Gerais e Goiás), \r\nrumo ao Mato Grosso.A rodovia também faz cruzamento com outras rodovias importantes como a BR-040 e a BR-354.',
	),
	array( // row #63
		'num_rodovia' => 367,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-367 é uma rodovia federal diagonal brasileira. Tem início em Santa Cruz Cabrália, na Bahia, e término em Gouveia, no estado de \r\nMinas Gerais.',
	),
	array( // row #64
		'num_rodovia' => 369,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-369 é uma rodovia federal diagonal brasileira. Anteriormente conhecida como Rodovia dos Cereais, a rodovia BR-369 inicia-se no \r\nentroncamento com a BR-494, no município de Oliveira em Minas Gerais, e atravessa o estado de São Paulo e parte do Paraná até a \r\ncidade de Cascavel. Entre os municípios atravessados pela BR-369 destacam-se: Alfenas, Poços de Caldas, São João da Boa Vista, \r\nAguaí, Pirassununga, Brotas, Jaú, Pederneiras, Bauru, Ourinhos, Londrina, Apucarana, Campo Mourão, Ubiratã e Cascavel. \r\n<br />\r\nNo estado de São Paulo, a rodovia é denominada primeiro em SP-215 e depois SP-225.',
	),
	array( // row #65
		'num_rodovia' => 373,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-373 é uma rodovia federal diagonal brasileira.',
	),
	array( // row #66
		'num_rodovia' => 374,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-374 é uma rodovia federal diagonal brasileira. Liga a cidade de São Paulo a Presidente Venceslau, no oeste paulista e possui \r\n573,9 km. Coincide com as rodovias estaduais Castelo Branco e Raposo Tavares.',
	),
	array( // row #67
		'num_rodovia' => 376,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-376 é uma rodovia diagonal brasileira, que liga Dourados, em Mato Grosso do Sul, a Garuva, em Santa Catarina. \r\nNo trecho paranaense, é conhecida como Rodovia do Café. No trecho entre Garuva e Curitiba, incorpora a BR-101.',
	),
	array( // row #68
		'num_rodovia' => 377,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-377 é uma rodovia federal diagonal brasileira.',
	),
	array( // row #69
		'num_rodovia' => 381,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-381 é uma rodovia federal brasileira que inicia na cidade de São Mateus, Espírito Santo, no entroncamento com a BR-101, \r\nchegando até a cidade de São Paulo, no entroncamento com a BR-116 Rodovia Presidente Dutra. Possui ao todo 1181 quilômetros, \r\ndos quais 95 são em São Paulo, 950 em Minas Gerais e 136 no Espírito Santo. O trecho compreendido entre Belo Horizonte e São Paulo \r\né denominado Rodovia Fernão Dias.',
	),
	array( // row #70
		'num_rodovia' => 383,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-383 é uma rodovia federal diagonal brasileira. Liga as cidades de Conselheiro Lafaiete em Minas Gerais, até a cidade de \r\nUbatuba em São Paulo.',
	),
	array( // row #71
		'num_rodovia' => 386,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-386 é uma rodovia federal brasileira que liga Canoas (na região metropolitana de Porto Alegre, capital do estado do Rio Grande do \r\nSul) com o município de Iraí (a extremo noroeste do estado, na divisa com Santa Catarina).\r\n<br />\r\nEm 19 de dezembro de 2007, através da Lei Nº 11.620, esta rodovia, que até então era chamada de "Tabaí-Canoas", "Rodovia da \r\nProdução", ou ainda de "Rodovia Presidente Kennedy", foi redenominada para “rodovia Governador Leonel de Moura Brizola".\r\n<br />\r\nA rodovia tem seu Km 0 no RS na divisa do Rio Grande do Sul com Santa Catarina, em Iraí, e o Km 445 com seu marco final, em Canoas, \r\nna chegada à BR-116.',
	),
	array( // row #72
		'num_rodovia' => 392,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-392 é uma importante rodovia brasileira que atravessa o centro do estado do Rio Grande do Sul. Nesta rodovia passa boa parte \r\nda matéria prima produzida no interior do estado. Seu início é no município de Rio Grande, no Super Porto, e segue até a cidade \r\nde Porto Xavier, na fronteira com a Argentina.\r\n<br />\r\nDurante toda a sua extensão, a BR-392 recebe diversos nomes. Essas variações são em decorrência da ligação entre diversos municípios.',
	),
	array( // row #73
		'num_rodovia' => 393,
		'tipo_rodovia' => 3,
		'descricao' => 'A BR-393, a antiga Rio-Bahia, é uma Rodovia Federal diagonal do Brasil. Seu ponto inicial fica na cidade fluminense de Barra Mansa, \r\ne o final, em Cachoeiro do Itapemirim (ES). O trecho entre Além Paraíba e Volta Redonda foi concedida a Rodovia do Aço (Grupo Acciona).',
	),
	array( // row #74
		'num_rodovia' => 401,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-401 é uma rodovia federal brasileira que liga a capital do estado de Roraima aos municípios de Normandia e Bonfim, ambos na \r\nfronteira com a Guiana. Possui 185 quilômetros de extensão, estando o Km 0 localizado em Boa Vista, no cruzamento com a BR-174, \r\npouco antes atravessar a ponte dos Macuxis.\r\n<br />\r\nAntes de Bonfim, a BR-401 segue para Normandia até o Km 185 (algumas fontes indicam como Km 199,2 ). \r\n<br />\r\nA rodovia é atendida por um posto da Polícia Rodoviária Federal antes da Ponte dos Macuxis, dentro do perímetro urbano de Boa Vista.',
	),
	array( // row #75
		'num_rodovia' => 402,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-402 é uma rodovia federal de ligação brasileira que deve interligar localidades próximas ao litoral dos estados do Maranhão, \r\nPiauí e Ceará.Alguns trechos ainda estão em implantação.',
	),
	array( // row #76
		'num_rodovia' => 403,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-403 é uma rodovia federal de ligação brasileira. Liga as cidades de Crateús e Acaraú no Ceará. Boa parte da rodovia é estadualizada.',
	),
	array( // row #77
		'num_rodovia' => 404,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-404 é uma rodovia federal de ligação brasileira, que deve ligar as cidades de Piripiri, no Piauí á Icó no Ceará. \r\nBoa parte do trecho ainda está em planejamento.',
	),
	array( // row #78
		'num_rodovia' => 405,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-405 é uma rodovia de ligação, que liga as cidades de Cajazeiras, na Paraíba e Mossoró, no Rio Grande do Norte. \r\nPode servir de rota alternatíva à BR-116.',
	),
	array( // row #79
		'num_rodovia' => 406,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-406 é uma rodovia federal de ligação brasileira. No caso dessa rodovia, localizada no Rio Grande do Norte, ela liga Natal a Macau, \r\ncidade conhecida pela produção de sal.',
	),
	array( // row #80
		'num_rodovia' => 407,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-407 é uma rodovia federal brasileira. É talvez a maior rodovia de ligação existente no Brasil, possuindo 1.482,6 km de extensão, \r\ncortando três estados: Bahia, Pernambuco e Piauí.\r\n<br />\r\nA rodovia tem início em Vitória da Conquista, passando, em seguida, pela região da Chapada Diamantina, e depois por municípios como \r\nSenhor do Bonfim.\r\n<br />\r\nA ponte sobre o Rio São Francisco, que divide as cidades de Juazeiro e Petrolina, é uma das divisas mais movimentada do Brasil.',
	),
	array( // row #81
		'num_rodovia' => 408,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-408 é uma rodovia federal brasileira. É uma rodovia de ligação, de curta extensão. Inicia-se em Campina Grande, Paraíba e \r\ntermina em Recife, Pernambuco.No lado pernambucano a rodovia está sendo duplicada entre as cidades de Recife a Carpina \r\nno trecho de 42 km. Grande parte da BR-408 ainda não foi implantada, principalmente no estado da Paraíba, onde o único trecho \r\npavimentado é o coincidente com a BR-230, que se encontra duplicado. Em Pernambuco a rodovia está pavimentada de Recife até \r\nTimbaúba',
	),
	array( // row #82
		'num_rodovia' => 409,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-409 será uma rodovia federal de ligação brasileira. No momento, ela praticamente não existe, mas segundo o planejamento, \r\nficaria localizada no Acre e ligaria as cidades de Feijó e Santa Rosa do Purus.',
	),
	array( // row #83
		'num_rodovia' => 410,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-410 é uma rodovia federal de ligação brasileira. É uma rodovia curta, de apenas 36 km, localizada na Bahia, e faz a ligação com \r\nas duas estradas mais importantes do nordeste baiano que são a BR-110(Ribeira do Pombal-BA) e a BR-116(Tucano-BA).',
	),
	array( // row #84
		'num_rodovia' => 411,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-411 é uma rodovia federal de ligação brasileira. É uma poucas rodovias federais do Brasil que nunca teve as suas obras iniciadas. \r\nFoi uma das rodovias lançadas pelo Plano de Integração Nacional, em 1970, e deveria se iniciar no entroncamento com a BR-307 \r\n(também inexistente na maior parte dos trechos), seguindo até a localidade de Palmeiras do Javari, às margens do Rio Javari, \r\nonde existe um pelotão de fronteira do exército. Se caso a rodovia existisse, esta estaria totalmente localizada no município de \r\nAtalaia do Norte, no Amazonas.',
	),
	array( // row #85
		'num_rodovia' => 412,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-412 é uma rodovia de ligação. É uma rodovia, relativamente curta, com sua localização restrita ao estado da Paraíba. \r\nTem início na BR-230, um pouco depois de Campina Grande, passa pelos municípios de Boa Vista, São João do Cariri, Serra Branca, \r\nSumé e termina em Monteiro, quando então, vira BR-110.',
	),
	array( // row #86
		'num_rodovia' => 413,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-413 é uma rodovia federal de ligação brasileira.',
	),
	array( // row #87
		'num_rodovia' => 414,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-414 é uma rodovia que liga os municípios de Niquelândia (GO) até Anápolis (no mesmo estado). \r\nPassa também por municípios como Corumbá de Goiás e Cocalzinho.\r\n<br />\r\nCruza com a BR-080 na altura do distrito de Dois Irmãos, sendo esta uma ligação com o Distrito Federal. \r\n<br />\r\nA BR-070 faz entroncamento com a BR-414 na cidade de Cocalzinho de Goiás. A BR-414 está totalmente pavimentada, porém já há \r\nmuitos buracos em toda extensão da pista devido ao fluxo intenso de caminhões carregados de carbonato de níquel, com destino a \r\nSão Paulo, óleo diesel e minério de níquel, que vem de Barro Alto para Niquelândia. Essa rodovia está planejada também para ligar \r\nPorangatu a Niquelândia, porém o processo está parado, sem previsão de implantação. Possui cerca 411,7 km.',
	),
	array( // row #88
		'num_rodovia' => 415,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-415 é uma rodovia federal do Brasil localizada no sudeste baiano. Liga Vitória da Conquista à Costa do Cacau (Ilhéus e Itabuna). \r\nPorém, no trecho compreendido entre Ilhéus e Itabuna o movimento é intenso devido a presença de muitas carretas bi-trem que \r\ndescarregam soja oriunda do Oeste Baiano no porto de Ilhéus, da existência da CEPLAC - Comissão Executiva do Plano da Lavoura \r\nCacaueira, dos bairros que ficam às margens da rodovia, como: Teotônio Vilela, Vila Nazaré, Banco da Vitória e Salobrinho este \r\núltimo que abriga a UESC - Universidade Estadual de Santa Cruz, além do alto índice de acidentes que ocorrem neste percurso de 33km. \r\n<br />\r\nO motorista também deve ficar atento a região da Serra do Marçal, próximo a Vitória da Conquista, pois é um trecho muito sinuoso e \r\ningreme com várias curvas perigosas.',
	),
	array( // row #89
		'num_rodovia' => 416,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-416 é uma rodovia federal de ligação brasileira. Liga os municípios de Novo Lino a São José da Laje, em Alagoas.',
	),
	array( // row #90
		'num_rodovia' => 417,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-417 é uma rodovia federal de ligação brasileira que cortaria a Ilha de Marajó, no Pará.',
	),
	array( // row #91
		'num_rodovia' => 418,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-418 é a principal ligação entre o nordeste de Minas Gerais e o litoral sul da Bahia. A estrada tem início em Teófilo Otoni, passa por \r\nNanuque e praticamente termina na BR-101, já no território baiano em Caravelas, mas o trecho entre a BR-101 e essa cidade, \r\npossui somente 23 km asfaltado (entre Caravelas e o povoado de Taquari) no sentido do litoral para a BR-101. \r\n<br />\r\nEntre Taquari e Juerana o serviço de terraplanagem encontra-se em fase adiantada. A previsão da conclusão das obras até Posto da \r\nMata é para 2012, conforme placa da obra localizada em frente à entrada do aeroporto de Caravelas).\r\n<br />\r\nÉ uma rodovia bem movimentada, pois muitos turistas, vindos das regiões Sudeste e Centro-Oeste do pais, utilizam a rodovia para ir a \r\nPorto Seguro, que é uma das cidades turísticas mais visitadas do Brasíl.',
	),
	array( // row #92
		'num_rodovia' => 419,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-419 é uma rodovia federal de ligação brasileira, localizada no Mato Grosso do Sul, próximo ao Pantanal. Inicia-se na BR-163 em \r\nRio Verde do Mato Grosso, atravessa cidades como Aquidauana e Nioaque e termina em Jardim. Faz Interseções com rodovias \r\nimportantes como a BR-262, BR-060 e BR-267.',
	),
	array( // row #93
		'num_rodovia' => 420,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-420 faz ligação entre as: BR-110, BR-324, BR-242 entre os municipios de Pojuca, Santo Amaro, Cachoeira, São Félix, Maragogipe, \r\nNazaré das Farinhas - BA-001, Jaguaripe, BR-101 até a BR-116, entre os municípios de Laje, Mutuípe, Jiquiriçá, Ubaíra, Santa Inês, \r\nItaquara até Jaguaquara, Região do Vale do Jiquiriçá, na Bahia.\r\n<br />\r\nO seu percuso é de 352,9 km, e agora encontra-se completamente asfaltada de Laje na BR-101 até Jaguaquara no Entroncamento \r\ncom a BR-116.',
	),
	array( // row #94
		'num_rodovia' => 421,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-421 é uma rodovia federal localizada no estado de Rondônia, que liga a BR-364 km 516 (trevo de entrada a Ariquemes) até a \r\ncidade de Buritis, passando por Monte Negro e Campo Novo de Rondônia.',
	),
	array( // row #95
		'num_rodovia' => 422,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-422 é uma rodovia federal de ligação brasileira.',
	),
	array( // row #96
		'num_rodovia' => 423,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-423 tem seu início oficial em Caruaru-PE. Nos primeiros quilometros, passa pela duplicada BR-232, até cidade São Caetano-PE. \r\nNa sequencia, a rodovia, segue em direção a Cachoeirinha, Lajedo e Garanhuns, considerada uma cidade com boa importância turística, \r\npelo fato de fazer frio nesta cidade.Essa rodovia será duplicada cerca de 80km entre são caetano-PE até Garanhuns-PE, a partir de 2013.\r\n<br />\r\nSeguindo, a rodovia atravessa parte do Agreste, e em seguida a região de Delmiro Gouveia, em Alagoas. o ponto final da rodovia, \r\npor enquanto, está em Paulo Afonso, na Bahia, mas ainda há planos desta rodovia se estender até Juazeiro.',
	),
	array( // row #97
		'num_rodovia' => 424,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-424 é uma rodovia federal brasileira, que corta várias cidades de Pernambuco e Alagoas. Existem planos de ligar o agreste \r\npernambucano ao litoral de Alagoas. Por enquanto, a rodovia, praticamente se resume ao trecho entre Arcoverde e Garanhuns. \r\n<br />\r\nEm Alagoas, a estrada é asfaltada a partir de Atalaia, mas a DNIT, não reconhece este trecho como a BR-424, e sim como a BR-316.',
	),
	array( // row #98
		'num_rodovia' => 425,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-425 é uma rodovia federal que liga Abunã (distrito de Porto Velho) a Guajará-Mirim, em Rondônia. No seu percurso passa pelo município de Nova Mamoré.',
	),
	array( // row #99
		'num_rodovia' => 426,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-426 é uma rodovia, localizada entre os estados de Pernambuco e Paraíba. É uma estrada que possui mais km de terra do que asfalto e atravessa pequenos municípios do oeste da Paraíba, até encontrar com a BR-230, próximo a Pombal.',
	),
	array( // row #100
		'num_rodovia' => 427,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-427 é uma rodovia de ligação, com início em Pombal, na Paraíba, e término em Currais Novos, no Rio Grande do Norte, quando a estrada passa a se denominar BR-226, que vai até Natal. É a estrada mais importante da região do Seridó.',
	),
	array( // row #101
		'num_rodovia' => 428,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-428 está localizada no Sertão de Pernambuco, entre as cidades de Petrolina e Cabrobó. Tem aproximadamente 190 km de extensão \r\ne é um trecho que chama muita atenção pelo alto índice de assaltos.',
	),
	array( // row #102
		'num_rodovia' => 429,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-429 é uma rodovia de ligação da região norte do Pais,fica no estado de Rondonia e liga seis municipios, sendo eles: Presidente \r\nMédici, Alvorada do Oeste, São Miguel do Guaporé, Seringueiras, São Francisco do Guaporé e Costa Marques que faz Fronteira com \r\na Bolivia.',
	),
	array( // row #103
		'num_rodovia' => 430,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-430 é uma rodovia federal brasileira, que liga as cidades baianas de Caetité a Barreiras. À altura da cidade de Bom Jesus da Lapa, \r\napós a Ponte Gercino Coelho, funde-se com a BR-349 por alguns quilômetros, passando para um trecho projetado até a cidade de \r\nBaianópolis.',
	),
	array( // row #104
		'num_rodovia' => 431,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-431 é uma rodovia federal de ligação brasileira que conecta a vila de Jundiá, na BR-174, à vila de Santa Maria do Boiaçu, ambas \r\nno município de Rorainópolis. A rodovia está totalmente situada no estado de Roraima.\r\n<br />\r\nAtualmente cerca de 45 quilômetros foram abertos e outros 80 são planejados. Um trecho foi aberto desde Jundiá para oeste, \r\nperdendo-se na mata densa; e o outro saindo de Santa Maria do Boiaçu para leste, também interrompido pela selva. Este hiato \r\nrepresenta o segmento ainda planejado. Há estradas-vicinais implantadas junto ao Boiaçu.\r\n<br />\r\nA rodovia atravessa a floresta amazônica e ainda não possui pavimentação. Anteriormente chamou-se RR-480, recebendo o nome \r\natual após a federalização da estrada',
	),
	array( // row #105
		'num_rodovia' => 432,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-432 é uma rodovia federal de ligação brasileira que corta o interior do estado de Roraima. Liga a rodovia BR-401 à BR-174 e BR-210, \r\nna altura da Vila Novo Paraíso (localidade conhecida por km 500), município de Caracaraí.\r\n<br />\r\nParcialmente asfaltada, conecta a cidade do Cantá e algumas vilas do município ao sistema rodoviário do Estado. Após, segue sem \r\npavimentação até o entroncamento com as BRs 174 e 210, totalizando 217,2 quilômetros.\r\n<br />\r\nAtravessa no seu trecho norte uma vegetação de cerrado (localmente denominado lavrado), chegando à floresta amazônica em seu \r\ntrecho centro-sul.',
	),
	array( // row #106
		'num_rodovia' => 433,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-433 é uma rodovia federal de ligação brasileira, que interliga a BR-401 (Km 183 da estrada Boa Vista–Normandia) à BR-174 \r\n(Km 676,5 da estrada Manaus–Venezuela), num total de 191 quilômetros sem pavimentação.\r\n<br />\r\nEstá totalmente localizada no estado de Roraima, no extremo norte do País. Em seu trajeto, que se inicia na cidade de Normandia, \r\npossui entrocamentos com a estradas estaduais RR-171, RR-319 e RR-407. Dá acesso ainda ao Lago Caracaranã, tido como um \r\ndos principais destinos turísticos de Roraima.',
	),
	array( // row #107
		'num_rodovia' => 434,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-434 é uma rodovia federal de ligação brasileira. Está localizada no Sertão Nordestino e é uma rodovia relativamente curta, \r\ncortando a divisa entre os estados da Paraíba e do Ceará.',
	),
	array( // row #108
		'num_rodovia' => 436,
		'tipo_rodovia' => 4,
		'descricao' => '',
	),
	array( // row #109
		'num_rodovia' => 437,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-437, conhecida também como Estrada do Cajueiro, é uma rodovia federal de ligação brasileira, pouco conhecida. Pois a rodovia, \r\nlocalizada na região da chapada do Apodi, entre os estados do Rio Grande do Norte e Ceará, não possui asfalto em toda a sua extensão. \r\n<br />\r\nAlém disso, a rodovia não atravessa praticamente nenhuma cidade(apenas 3 vilarejos, no lado potiguar).',
	),
	array( // row #110
		'num_rodovia' => 440,
		'tipo_rodovia' => 4,
		'descricao' => '',
	),
	array( // row #111
		'num_rodovia' => 447,
		'tipo_rodovia' => 4,
		'descricao' => '',
	),
	array( // row #112
		'num_rodovia' => 448,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-448, também chamada Rodovia do Parque é uma rodovia federal no Estado do Rio Grande do Sul, entre Sapucaia do Sul e Porto \r\nAlegre, a oeste da BR-116, para desafogar o trânsito desta nos horários de pico na Região Metropolitana. Tem o nome de Rodovia \r\ndo Parque por passar atrás do Parque de Exposições Assis Brasil, em Esteio, onde ocorre anualmente a Expointer.\r\n<br />\r\nA construção da rodovia, com duração de 30 meses, tem previsão de inauguração em 2013. A obra é realizada com R$ 932,6 milhões \r\nem recursos do PAC. A via será dividida em três trechos, que irão do entroncamento da BR-116 com a RS-118, em Sapucaia do Sul, \r\naté o entroncamento da BR-116 com a BR-290, em Porto Alegre. Estão incluídos na obra viadutos (como os que darão acesso aos \r\nmunicípios de Canoas e Esteio), pontes (como as que serão construídas sobre o rio Gravataí e sobre o arroio Sapucaia), \r\ne passagens inferiores rodoviárias e ferroviárias, com extensão total de 22,3 km.',
	),
	array( // row #113
		'num_rodovia' => 450,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-450 é uma rodovia de ligação brasileira. Está totalmente localizada dentro do Distrito Federal e é concomitante com a rodovia \r\ndistrital DF-003, Estrada Parque de Indústria e Abastecimento (EPIA). Possui uma extensão total de 36,8 Km e é considerada \r\ncomo uma das menores rodovias federais do Brasil.',
	),
	array( // row #114
		'num_rodovia' => 451,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-451 é uma rodovia federal brasileira e deveria ser uma rodovia que ligaria o norte ao leste de Minas Gerais, mas a rodovia apresenta \r\nvários trechos sem asfalto ou ainda em implantação.',
	),
	array( // row #115
		'num_rodovia' => 452,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-452 é uma rodovia localizada na Mesorregião do Triângulo Mineiro e Alto Paranaíba, que faz a ligação de Uberlândia e outras \r\ncidades da rota com a rodovia BR-262, sentido a Belo Horizonte. A rodovia inicia em Rio Verde e termina em Araxá, com extensão de \r\n508,9 km.',
	),
	array( // row #116
		'num_rodovia' => 453,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-453, chamada também de Rota do Sol, é uma rodovia federal de ligação brasileira que liga o litoral do Rio Grande do Sul à Serra \r\nGaúcha. Liga Venâncio Aires à Terra de Areia e tem aproximadamente 300 km de extensão.\r\n<br />\r\nObra idealizada em 1931 e iniciada em 1972, a Rota do Sol foi concluída em 2008. A distância entre Caxias do Sul e Terra de Areia, \r\npela Rota do Sol, é de 170 km.\r\n<br />\r\nA rodovia se configura em um grande atalho às praias gaúchas, visto que, anteriormente, todo o trânsito que se dirigia à região, \r\nprecisava obrigatoriamente ir para a capital Porto Alegre e/ou percorrer a Freeway (BR-290), que era o único acesso asfaltado ao local. \r\nCom isso, houve uma melhor distribuição do trânsito pelo estado.',
	),
	array( // row #117
		'num_rodovia' => 454,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-454 é uma rodovia federal de ligação brasileira, localizado no Pantanal Sul-Matogrossense. Fará ligação entre a BR-262 e ao Forte Coimbra.',
	),
	array( // row #118
		'num_rodovia' => 455,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-455 é uma rodovia federal de ligação brasileira. Inicia-se em Uberlândia, Minas Gerais, e termina na rodovia BR-364, município de Planura, próximo à divisa com São Paulo. Passa ainda pelos municípios de Prata (mais especificamente no distrito de Patrimônio), Campo Florido e Pirajuba, todos em Minas Gerais. Possui comprimento de 137,3 km.',
	),
	array( // row #119
		'num_rodovia' => 456,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-456 é uma rodovia federal de ligação brasileira. Na verdade, ele recebe a denominação da SP-310, no trecho entre Nhandeara e Matão, passando por São José do Rio Preto.',
	),
	array( // row #120
		'num_rodovia' => 457,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-457 é uma rodovia federal de ligação brasileira, localizado em Goiás. Fará ligação entre a BR-050, na altura de Cristalina e a capital Goiânia, sendo que boa parte da rodovia ainda não recebeu asfalto.',
	),
	array( // row #121
		'num_rodovia' => 458,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-458 está localizada no leste mineiro é uma ligação entre a BR-116 e a cidade de Ipatinga e, indiretamente, outras cidades do \r\nVale do Aço.',
	),
	array( // row #122
		'num_rodovia' => 459,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-459 é uma rodovia federal brasileira que liga Poços de Caldas, em Minas Gerais, a Lorena, no estado de São Paulo. \r\nEstá planejada sua extensão até o município de Angra dos Reis, no estado do Rio de Janeiro.',
	),
	array( // row #123
		'num_rodovia' => 460,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-460 é uma rodovia federal de ligação brasileira no estado de Minas Gerais. Com 84 km de extensão , a rodovia faz parte do \r\nCircuito das Águas e liga a BR-267 em Cambuquira à BR-354 em São Lourenço. A rodovia está localizada na Mesorregião do Sul e \r\nSudoeste de Minas e passa pelos municípios de Cambuquira, Lambari, Jesuânia, Olímpio Noronha, Carmo de Minas e São Lourenço.',
	),
	array( // row #124
		'num_rodovia' => 461,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-461 é uma rodovia federal de ligação brasileira.A rodovia planeja ligar os municípios de Ituiutaba a Iturama, cortando assim, o pontal do Triângulo.',
	),
	array( // row #125
		'num_rodovia' => 462,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-462 é uma rodovia federal de ligação brasileira. Faz ligação entre Patrocínio e a BR-262.',
	),
	array( // row #126
		'num_rodovia' => 463,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-463 é uma rodovia federal de ligação brasileira. Iniciando-se em Dourados, é a principal via de acesso a Ponta Porã e ao Paraguai via Pedro Juan Caballero.',
	),
	array( // row #127
		'num_rodovia' => 464,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-464 é uma rodovia federal de ligação brasileira. Planeja fazer ligação entre o Triângulo Mineiro e a Serra da Canastra, passando por Uberaba. Por enquanto, o único trecho já existente, liga Uberaba a BR-428, próximo a Sacramento.',
	),
	array( // row #128
		'num_rodovia' => 465,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-465, Antiga Estrada (ou Rodovia) Rio-São Paulo é uma rodovia de ligação situada no estado do Rio de Janeiro, na região sudeste \r\ndo Brasil, com extensão de 31,9 quilômetros.',
	),
	array( // row #129
		'num_rodovia' => 466,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-466 corta a região central do Paraná, a partir de Apucarana, e praticamente se encerra em Guarapuava, pois o trecho entre essa \r\ncidade até Porto União, ainda está em planejamento.',
	),
	array( // row #130
		'num_rodovia' => 467,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-467 passa pelo mesmo trajeto da BR-163, portanto quase confundindo as nomenclaturas. No trecho entre Cascavel e Toledo, no Paraná está duplicado desde o final do ano de 2006.',
	),
	array( // row #131
		'num_rodovia' => 468,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-468 é uma rodovia federal do Brasil que fica localizada no Noroeste Gaúcho. Liga Palmeira das Missões à fronteira brasileira com a Argentina.',
	),
	array( // row #132
		'num_rodovia' => 469,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-469 é uma rodovia brasileira situada dentro do limite do município de Foz do Iguaçu, no Paraná. Inicia a 4 km do centro da cidade, \r\nna aduana argentina, e termina nas Cataratas do Iguaçu, totalizando 19 km, passando boa parte de seu leito dentro do Parque \r\nNacional do Iguaçu.\r\n<br />\r\nA partir de 2007 a rodovia faz parte do percurso da Meia Maratona das Cataratas, com o seu grande atrativo que é a beleza do \r\ntrajeto e o famoso ponto turístico, o Parque Nacional do Iguaçu.',
	),
	array( // row #133
		'num_rodovia' => 470,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-470 é uma rodovia de ligação no Sul do Brasil. Seu projeto oficial contempla 472,3 km entre Navegantes (SC) e Camaquã (RS). \r\nParte do trecho que corta o estado do Rio Grande do Sul está sob administração do governo estadual, sendo denominada RSC-470.\r\n<br />\r\nÉ uma rodovia de pista simples, importante historicamente para a ligação do Planalto e do Oeste catarinense ao litoral. É a principal \r\n"artéria" do Vale do Itajaí e também uma das principais vias de acesso ao Porto de Itajaí e ao Aeroporto de Navegantes. \r\n<br />\r\nApresenta trechos sinuosos e mal-sinalizados no estado de Santa Catarina além de áreas não-pavimentadas ou inexistentes no Rio \r\nGrande do Sul. É excessivamente movimentada num trecho de aproximadamente 40 km entre Gaspar (bairro do Belchior), \r\nBlumenau (bairro do Tribess) e Indaial (SC), registrando-se a ocorrência diária de acidentes.',
	),
	array( // row #134
		'num_rodovia' => 471,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-471 é uma rodovia federal do Brasil localizada no extremo sul do país, no estado do Rio Grande do Sul. Tem seu início em Soledade, \r\npassa por Santa Cruz do Sul, Encruzilhada do Sul, Pelotas, Quinta (distrito de Rio Grande), Santa Vitória do Palmar e se encerra no Chuí, \r\nque é a cidade mais meridional do Brasil. A BR-471 corta a Estação Ecológica do Taim, uma das principais estações ecológicas do Rio \r\nGrande do Sul.',
	),
	array( // row #135
		'num_rodovia' => 472,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-472 é uma rodovia federal do Brasil que corta o extremo oeste gaúcho. Inicia-se em Frederico Westphalen, mas só ganha \r\nimportância a partir de São Borja. A partir daí, percorre a região do rio Uruguai e passa em Uruguaiana, que é uma cidade \r\nmovimentada pelo fato de muitos carros e caminhões argentinos saírem do Brasil, por este município. A BR-472 se encerra em \r\nBarra do Quaraí, aonde há uma tríplice fronteira entre Brasil, Argentina e Uruguai.',
	),
	array( // row #136
		'num_rodovia' => 473,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-473 é uma rodovia federal de ligação brasileira, não possui pedágios e possui uma balsa, em Santa Isabel do Sul, distrito de \r\nArroio Grande.',
	),
	array( // row #137
		'num_rodovia' => 474,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-474 é uma rodovia federal de ligação brasileira. Seu trajeto passa por cidades como Caratinga, Ipanema e Aimorés, interligando as regiões mineiras do Vale do Aço, médio Rio Doce e Zona da Mata até a divisa com o Espírito Santo.',
	),
	array( // row #138
		'num_rodovia' => 475,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-475 é uma rodovia federal de ligação brasileira. Faz ligação entre o litoral e a serra catarinense, mais precisamente, entre Tubarão e Lages. Alguns trechos ainda estão sendo planejados e a estrada possui 212 km de extensão.',
	),
	array( // row #139
		'num_rodovia' => 476,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-476 se inicia no Vale do Ribeira, na divisa de São Paulo com o Paraná. Possui 366 km, desde o quilômetro 0, até a divisa do \r\nParaná com Santa Catarina, onde passa a se denominar BR-153.\r\n<br />\r\nDesde o Trevo do Atuba até o bairro do Pinheirinho, no perímetro urbano de Curitiba, ela assumiu o antigo trecho da BR-116, \r\napós a construção do Contorno Leste, anel rodoviário que desvia o trânsito da capital, desde o município de Quatro Barras.\r\n<br />\r\nDa cidade de Adrianópolis até Curitiba, a rodovia é denominada Estrada da Ribeira. De Curitiba até União da Vitória, ela é denominada \r\nRodovia do Xisto, por ser importante ligação com a região de São Mateus do Sul, importante pólo de extração do xisto betuminoso.',
	),
	array( // row #140
		'num_rodovia' => 477,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-477 é uma rodovia de ligação em Santa Catarina. Parcialmente pavimentada, tem início no entroncamento das rodovias BR-280 e \r\nBR-116 em Canoinhas e término em Blumenau no entroncamento com a SC-418. Representa a ligação do Vale do Itajaí ao Planalto \r\nNorte Catarinense. Parte do seu trajeto sobrepõe-se à BR-470 e a maior parte do trecho entre Doutor Pedrinho e Papanduva, \r\njustamente o trecho de transposição da Serra do Mar, que separa a duas regiões, encontra-se em pavimentação. Atualmente a \r\nrodovia está sob jurisdição estadual, conhecida como SC-477.',
	),
	array( // row #141
		'num_rodovia' => 478,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-478 é uma rodovia federal de ligação brasileira. Boa parte do trecho é de jurisdição estadual e atravessa importantes cidades \r\ndo estado de São Paulo, como Limeira, aonde a rodovia começa, e Sorocaba. Coincide com a BR-116, na altura de Registro. \r\nO ponto final, se localiza na altura de Pariquera-Açu.',
	),
	array( // row #142
		'num_rodovia' => 479,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-479 é uma rodovia federal brasileira que liga Brasília, a Januária, no norte de Minas Gerais. No entanto há poucos trechos asfaltados.',
	),
	array( // row #143
		'num_rodovia' => 480,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-480 é uma rodovia de ligação que tem seu início em Pato Branco, no Paraná e vai até encontrar com a BR-153, próximo a Erechim. \r\nNo seu trajeto, passa pela cidade de Xanxerê, onde há um entroncamento com a BR-282, que corta o estado de Santa Catarina.\r\n<br />\r\nEm Santa Catarina é denominada SC-480, pois esta é administrada pelo estado.',
	),
	array( // row #144
		'num_rodovia' => 481,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-481 é uma rodovia federal de ligação brasileira, localizada na região central do Rio Grande do Sul.',
	),
	array( // row #145
		'num_rodovia' => 482,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-482 é uma rodovia federal brasileira que tem início no município de Itapemirim (localidade de Safra) - ES e término na cidade de \r\nConselheiro Lafaiete - MG.\r\n<br />\r\nA extensão total da rodovia é de 406,8 km, ligando cidades importantes como Cachoeiro de Itapemirim-ES, Carangola-MG, Conselheiro \r\nLafaiete-MG e Viçosa-MG. Sendo assim, sua principal função é ligar os dois Estados, tornando-se uma das opções de acesso mútuo aos \r\nEstados de Minas Gerais e Espírito Santo. Para os mineiros da microrregião de Carangola, a rodovia é a principal via de acesso às praias \r\ndo litoral do Espírito Santo.',
	),
	array( // row #146
		'num_rodovia' => 483,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-483 é uma rodovia federal de ligação brasileira, localizada no Sul de Goiás. Dá acesso a importantes cidades que margeiam o Rio Paranaíba, como Itumbiara, Cachoeira Dourada e São Simão.',
	),
	array( // row #147
		'num_rodovia' => 484,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-484 é uma rodovia federal de ligação brasileira do estado do Espírito Santo. Inicia-se em Afonso Cláudio e liga o Centro da cidade \r\naos demais distritos e cidades vizinhas. A BR termina no estado do Rio de Janeiro.\r\n<br />\r\nÉ uma rodovia de tráfego médio e velocidade média. A BR-484 é uma das principais rodovias da região serrana do estado, visto que \r\ncorta metade da cidade de Afonso Cláudio e interliga a BR-259 a BR-262. Além disso, interliga também cidades como Colatina, Laranja \r\nda Terra e Santa Maria de Jetibá, entre outras, a Afonso Cláudio. Faz ligação semi-direta com a ES-165, que liga o Centro de Afonso \r\nCláudio a BR-262. Faz intersessão em apenas um trecho da ES-165, também dentro do município de Afonso Cláudio, completando cerca \r\nde 15 km de interseção onde continua seu trajeto. até o distrito de Serra Pelada',
	),
	array( // row #148
		'num_rodovia' => 485,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-485 é uma rodovia federal de ligação brasileira que liga o município de Itatiaia (RJ) à localidade de Garganta do Registro, localizada \r\nna divisa entre os estados brasileiros do Rio de Janeiro e de Minas Gerais, no entroncamento com a BR-354. No km 36 da BR-485 \r\n(trecho do estado do Rio de Janeiro), está localizado o ponto mais alto de todas as rodovias do Brasil, onde a rodovia atinge a sua \r\naltitude máxima de 2.460 m.1 Este ponto fica situado logo após o acesso para o Morro da Antena, no sentido do Abrigo Rebouças.\r\n<br />\r\nO pequeno acesso de 1,4 km que sobe o Morro da Antena rumo à estação de rádio da Eletrobras Furnas (que fica no topo da montanha), \r\né a estrada (rural) mais alta do país, onde se pode chegar até a altitude de 2.662 m, utilizando-se um veículo.',
	),
	array( // row #149
		'num_rodovia' => 486,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-486, também conhecida como Rodovia Antônio Heil, é uma rodovia de ligação que interliga o município de Itajaí, a partir da BR-101, \r\ncom o município de Presidente Nereu, passando por Brusque e Botuverá, todos localizados na região do Vale do Itajaí, numa extensão \r\nde aproximadamente 108 km. Apenas o trecho Itajaí-Brusque é pavimentado, sendo o restante leito natural. Também há o trecho entre \r\nVidal Ramos e Ituporanga, indo até a BR-282.',
	),
	array( // row #150
		'num_rodovia' => 487,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-487 liga Porto Felicidade, no Mato Grosso do Sul à Ponta Grossa, no Paraná. Seu trecho é bastante precário, sendo que \r\naproximadamente 80% está no estado paranaense. Conhecida como Rodovia Boiadeira, foi muito usada para o transporte de gado. \r\nGrande parte do seu trecho é não-pavimentado, o que ocasiona transtornos à população que vive às suas margens, alternando \r\npoeira em períodos de seca e lama no período chuvoso.',
	),
	array( // row #151
		'num_rodovia' => 488,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-488 é uma rodovia de ligação. Esta rodovia liga a Rodovia Presidente Dutra (BR-116) ao Santuário Nacional de Nossa Senhora \r\nAparecida, em Aparecida, SP. Tem apenas 5,9 km de extensão , sendo a menor rodovia federal do país.',
	),
	array( // row #152
		'num_rodovia' => 489,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-489 é uma rodovia federal de ligação brasileira. É um trecho de 51 km ligando Prado na Bahia á BR-101, próximo a Itamaraju.',
	),
	array( // row #153
		'num_rodovia' => 490,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-490 é uma rodovia federal de ligação brasileira, que na verdade se denomina GO-213, em sua maior parte. Atravessa as cidades turísticas de Caldas Novas e Rio Quente.',
	),
	array( // row #154
		'num_rodovia' => 491,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-491 é uma rodovia federal brasileira, situada no estado de Minas Gerais. Com 263,6 km de extensão, é toda pavimentada em \r\npista simples, exceto em trecho na zona urbana de Varginha, onde é duplicada.\r\n<br />\r\nA BR-491 inicia no entroncamento com as rodovias BR-265 e MG-050, em São Sebastião do Paraíso, e termina no entroncamento com a \r\nBR-381 em Três Corações, passando pelos municípios de Itamogi, Monte Santo de Minas, Guaranésia, Guaxupé, Muzambinho, \r\nMonte Belo, Areado, Alfenas, Paraguaçu, Elói Mendes e Varginha.',
	),
	array( // row #155
		'num_rodovia' => 492,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-492 é uma rodovia federal de ligação brasileira que liga o Norte Fluminense á região serrana do estado. No geral, a jurisdição desta rodovia ainda é estadual.',
	),
	array( // row #156
		'num_rodovia' => 493,
		'tipo_rodovia' => 4,
		'descricao' => 'O Arco Metropolitano do Rio de Janeiro (também conhecido apenas como Arco Metropolitano) é uma autoestrada que será construída \r\nno entorno da Região Metropolitana do Rio de Janeiro com a missão de desviar o intenso tráfego de veículos que apenas atravessam \r\na cidade do Rio de Janeiro diminuindo assim, os congestionamentos nas principais vias acessos da cidade. O Arco Metropolitano do Rio \r\nde Janeiro seguirá o mesmo percurso formado pelas rodovias BR-493, parte da BR-116 e RJ-109. \r\n<br />\r\nLigará as cidades de Itaboraí, Guapimirim, Magé, Duque de Caxias, Nova Iguaçu, Japeri, Seropédica e Itaguaí. O projeto Arco \r\nMetropolitano se encontra com menos do que 50% das obras concluidas e nenhum trecho inaugurado após 5 anos do início das obras',
	),
	array( // row #157
		'num_rodovia' => 494,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-494 é uma rodovia federal brasileira que passa pelos estados de Minas Gerais e do Rio de Janeiro. Ela liga a BR-262 em Nova \r\nSerrana à BR-101 em Angra dos Reis.\r\n<br />\r\nAo longo de sua extensão, passa por diversas cidades, entre elas Divinópolis, que possui um importante pólo de moda, São João del-Rei, \r\ncidade natal de Tancredo Neves cujos principais atrativos são o turismo e o comércio, e Volta Redonda, no estado do Rio de Janeiro, \r\na maior cidade do Sul Fluminense.\r\n<br />\r\nA rodovia ainda tem trechos em planejamento e parte de seu trajeto é compartilhado com rodovias estaduais, entre elas a RJ-153, \r\na RJ-155 e a MG-457, e com rodovias federais, entre elas a BR-381 e a BR-383.',
	),
	array( // row #158
		'num_rodovia' => 495,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-495 é conhecida com Estrada das Hortências. Liga os municípios de Teresópolis (Bairro do Quebra-Frascos) e Petrópolis \r\n(Itaipava na antiga Estrada União e Indústria).\r\n<br />\r\nCom 33,4km de extensão e altitude máxima em torno dos 1.500m, situa-se na Serra dos Órgãos; a rodovia é sinuosa e sem acostamento. \r\nPossui rampas íngremes e curvas fechadas. A região é de serra é sujeita a neblina. A sinalização é precária. Até 1959, com a construção \r\nda Rodovia Rio-Teresópolis, era por ela que se chegava em Teresópolis vindo do Rio de Janeiro.',
	),
	array( // row #159
		'num_rodovia' => 496,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-496 está localizada no norte de Minas Gerais. Liga a BR-365, com a BR-135. Pode ser considerada uma importante ligação entre \r\na região de Pirapora, com a capital mineira, visto que após o termino desta rodovia, em Corinto, se encontra com a BR-135, \r\nque por sua vez, encontrará com a BR-040, na altura de Paraopeba.',
	),
	array( // row #160
		'num_rodovia' => 497,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-497 é uma rodovia de ligação entre Uberlândia e Carneirinho (cidade que fica na Microrregião de Frutal, no Triângulo Mineiro) \r\ne tem um total de 353 km de extensão.\r\n<br />\r\nPassa pelas seguintes cidades: Uberlândia (Zona Oeste), Prata, Campina Verde, Iturama e Carneirinho (todas em Minas Gerais), \r\naté na divisa com a cidade de Paranaíba, no Mato Grosso do Sul.',
	),
	array( // row #161
		'num_rodovia' => 498,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-498 é uma rodovia federal de ligação brasileira.',
	),
	array( // row #162
		'num_rodovia' => 499,
		'tipo_rodovia' => 4,
		'descricao' => 'A BR-499, também nomeada de Rodovia Historiador Osvaldo Henrique Castello Branco, é uma rodovia federal de ligação brasileira \r\nque se encontra no município de Santos Dumont, Minas Gerais. Tem 14,9 km de extensão e liga o centro da cidade de Santos Dumont \r\nà Fazenda Cabangu,1 local onde nasceu o aviador Santos Dumont, e que hoje abriga o Museu de Cabangu. Por este motivo, a \r\nBR-499 é uma rodovia de caráter bastante peculiar para os padrões brasileiros, tal como a BR-488, localizada em Aparecida (SP).',
	),
	array( // row #163
		'num_rodovia' => 600,
		'tipo_rodovia' => 6,
		'descricao' => 'A BR-600 é uma rodovia federal de ligação do Brasil e tem a extensão de 6 km, pista dupla com acostamento, em bom estado de \r\nconservação e sinalização. Está situada no perímetro urbano de Foz do Iguaçu (Paraná), fazendo a ligação do centro da cidade \r\naté a Hidrelétrica de Itaipu. A rodovia também é chamada de Avenida Tancredo Neves. Serve de corredor turístico e universitário, \r\nutilizada por trabalhadores da Itaipu e moradores dos bairros e condomínios às margens da rodovia. A velocidade máxima permitida \r\nem seu trecho é de 80 km/h.',
	),
	array( // row #164
		'num_rodovia' => 610,
		'tipo_rodovia' => 6,
		'descricao' => 'A BR-610, chamada de Rodovia Helio Smidt é a denominação que recebe a rodovia SP-19/BR-610 em toda sua extensão. \r\nEla faz a ligação da Rodovia Ayrton Senna (SP-70) ao Aeroporto Internacional de São Paulo/Guarulhos, tendo uma interseção \r\ncom a Rodovia Presidente Dutra (BR-116).\r\n<br />\r\nÉ composta por duas pistas com duas faixas de tráfego cada, separadas por canteiro central. Com capacidade de mais de 4 mil veículos \r\npor hora em cada sentido, estima-se que 22 mil veículos por dia usem a rodovia que tem pouco mais de 5 km de extensão.',
	),
);

$resultados = array(
    'BR-116/SP',
    'BR-381/MG',
    'BR-101/SC',
    'BR-101/RJ',
    'BR-116/RJ',
    'BR-116/RS',
    'BR-277/PR',
    'BR-376/PR',
    'BR-040/MG',
    'BR-101/ES',
    'BR-282/SC',
    'BR-040/RJ',
    'BR-101/PE',
    'BR-470/SC',
    'BR-230/PB',
    'BR-364/RO',
    'BR-116/BA',
    'BR-324/BA',
    'BR-116/PR',
    'BR-101/BA',
    'BR-153/GO',
    'BR-316/PA',
    'BR-116/MG',
    'BR-369/PR',
    'BR-476/PR',
    'BR-262/MG',
    'BR-262/ES',
    'BR-101/RN',
    'BR-290/RS',
    'BR-364/MT',
    'BR-060/GO',
    'BR-232/PE',
    'BR-381/SP',
    'BR-386/RS',
    'BR-116/CE',
    'BR-163/MS',
    'BR-343/PI',
    'BR-365/MG',
    'BR-153/SP',
    'BR-222/CE',
    'BR-393/RJ',
    'BR-280/SC',
    'BR-050/MG',
    'BR-101/SE',
    'BR-285/RS',
    'BR-135/MA',
    'BR-316/PI',
    'BR-316/AL',
    'BR-163/MT',
    'BR-153/TO',
    'BR-163/PR',
    'BR-116/SC',
    'BR-040/GO',
    'BR-392/RS',
    'BR-304/RN',
    'BR-262/MS',
    'BR-101/PB',
    'BR-070/MT',
    'BR-010/MA',
    'BR-319/RO',
    'BR-287/RS',
    'BR-101/AL',
    'BR-267/MG',
    'BR-135/MG',
    'BR-153/MG',
    'BR-153/PR',
    'BR-242/BA',
    'BR-020/CE',
    'BR-316/MA',
    'BR-235/SE',
    'BR-251/MG',
    'BR-158/RS',
    'BR-110/BA',
    'BR-104/PE',
    'BR-020/DF',
    'BR-364/AC',
    'BR-230/PA',
    'BR-020/GO',
    'BR-459/MG',
    'BR-158/PR',
    'BR-373/PR',
    'BR-104/AL',
    'BR-428/PE',
    'BR-101/RS',
    'BR-153/RS',
    'BR-222/MA',
    'BR-356/RJ',
    'BR-493/RJ',
    'BR-465/RJ',
    'BR-364/GO',
    'BR-293/RS',
    'BR-070/GO',
    'BR-267/MS',
    'BR-158/MS',
    'BR-407/BA',
    'BR-226/RN',
    'BR-471/RS',
    'BR-040/DF',
    'BR-070/DF',
    'BR-104/PB',
    'BR-158/GO',
    'BR-174/MT',
    'BR-467/PR',
    'BR-050/GO',
    'BR-452/MG',
    'BR-259/ES',
    'BR-407/PE',
    'BR-423/PE',
    'BR-480/SC',
    'BR-101/SP',
    'BR-367/BA',
    'BR-452/GO',
    'BR-010/PA',
    'BR-060/DF',
    'BR-408/PE',
    'BR-414/GO',
    'BR-153/SC',
    'BR-354/MG',
    'BR-272/PR',
    'BR-472/RS',
    'BR-174/RR',
    'BR-316/PE',
    'BR-230/MA',
    'BR-158/MT',
    'BR-110/RN',
    'BR-406/RN',
    'BR-174/AM',
    'BR-424/PE',
    'BR-222/PA',
    'BR-163/PA',
    'BR-356/MG',
    'BR-210/AP',
    'BR-155/PA',
    'BR-463/MS',
    'BR-135/BA',
    'BR-487/PR',
    'BR-163/SC',
    'BR-364/MG',
    'BR-474/MG',
    'BR-146/MG',
    'BR-405/RN',
    'BR-330/BA',
    'BR-060/MS',
    'BR-459/SP',
    'BR-230/PI',
    'BR-450/DF',
    'BR-304/CE',
    'BR-116/PE',
    'BR-226/TO',
    'BR-080/GO',
    'BR-393/ES',
    'BR-468/RS',
    'BR-156/AP',
    'BR-226/MA',
    'BR-423/AL',
    'BR-427/RN',
    'BR-488/SP',
    'BR-158/SC',
    'BR-020/BA',
    'BR-480/RS',
    'BR-242/TO',
    'BR-308/PA',
    'BR-407/PI',
    'BR-460/MG',
    'BR-469/PR',
    'BR-361/PB',
    'BR-402/PI',
    'BR-317/AC',
    'BR-495/RJ',
    'BR-280/PR',
    'BR-354/RJ',
    'BR-418/BA',
    'BR-453/RS',
    'BR-174/RO',
    'BR-412/PB',
    'BR-110/PE',
    'BR-251/DF',
    'BR-359/MS',
    'BR-222/PI',
    'BR-319/AM',
    'BR-401/RR',
    'BR-377/RS',
    'BR-402/MA',
    'BR-410/BA',
    'BR-405/PB',
    'BR-470/RS',
    'BR-404/PI',
    'BR-419/MS',
    'BR-447/ES',
    'BR-429/RO',
    'BR-427/PB',
    'BR-153/PA',
    'BR-424/AL',
    'BR-230/TO',
    'BR-251/GO',
    'BR-420/BA',
    'BR-110/PB',
    'BR-135/PI',
    'BR-020/PI',
    'BR-230/CE',
    'BR-158/PA',
    'BR-116/PB',
    'BR-485/RJ',
    'BR-235/BA',
    'BR-110/AL',
    'BR-432/RR',
    'BR-416/AL',
    'BR-349/BA',
    'BR-000/RJ',
    'BR-230/AM',
    'BR-030/BA',
    'BR-425/RO',
    'BR-226/CE',
    'BR-560/BA',
    'BR-000/SP',
    'BR-221/SP',
    'BR-580/GO',
    'BR-617/MG',
    'BR-352/RJ',
    'BR-028/SC',
    'BR-634/ES',
    'BR-004/MG',
    'BR-000/PB',
    'BR-415/BA',
    'BR-654/PA',
    'BR-000/GO',
    'BR-661/GO',
    'BR-140/PR',
    'BR-004/RJ',
    'BR-462/MG',
    'BR-426/PB',
    'BR-505/SC',
    'BR-552/GO',
    'BR-000/ES',
    'BR-183/RS',
    'BR-000/MG',
    'BR-259/MG',
    'BR-270/MG',
    'BR-265/MG',
    'BR-178/RS',
    'BR-687/MG',
    'BR-343/RN',
    'BR-499/ES',
    'BR-349/PR',
    'BR-501/RN',
    'BR-489/SC',
    'BR-084/SC',
    'BR-473/RS',
    'BR-000/RS',
    'BR-241/SC'
);

foreach($infodprf_rodovias as $rodovia){
    array_push($resultados, 'BR-'.((strlen($rodovia['num_rodovia']) == 2) ? '0'.$rodovia['num_rodovia'] : $rodovia['num_rodovia']));
    array_push($resultados, 'BR'.((strlen($rodovia['num_rodovia']) == 2) ? '0'.$rodovia['num_rodovia'] : $rodovia['num_rodovia']));
}
ksort($resultados);
echo json_encode($resultados);

?>